In [3]:
!git clone https://github.com/AnalyticsKnight/yemoonsaBigdata

Cloning into 'yemoonsaBigdata'...
remote: Enumerating objects: 743, done.
remote: Counting objects: 100% (144/144), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 743 (delta 85), reused 63 (delta 63), pack-reused 599 (from 1)
Receiving objects: 100% (743/743), 11.86 MiB | 18.83 MiB/s, done.
Resolving deltas: 100% (360/360), done.

In [4]:
import pandas as pd

In [14]:
data1 = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.01.01-students_scores.csv')
data1

     student id  Statistics  DataScience  MachineLearning  EnglishLiterature
0             1         NaN         54.0             94.0               62.0
1             2        76.0         16.0             80.0                NaN
2             3         6.0          NaN             68.0               45.0
3             4        84.0         30.0             76.0                NaN
4             5         NaN         53.0             33.0               90.0
..          ...         ...          ...              ...                ...
995         996        33.0          3.0              NaN               86.0
996         997        50.0         33.0              3.0                NaN
997         998        77.0         34.0             79.0                NaN
998         999        43.0         97.0             30.0                NaN
999        1000         NaN         41.0             28.0                9.0

[1000 rows x 5 columns]

In [15]:
print(data1.isnull().sum())

student id             0
Statistics           227
DataScience          291
MachineLearning      231
EnglishLiterature    251
dtype: int64

In [16]:
statistics = data1['Statistics'].dropna()

In [17]:
statistics

1      76.0
2       6.0
3      84.0
5      18.0
6      26.0
       ...
994    65.0
995    33.0
996    50.0
997    77.0
998    43.0
Name: Statistics, Length: 773, dtype: float64

In [11]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()
statistics = pd.DataFrame(statistics)
statistics = scaler.fit_transform(statistics)
print(statistics)

[[ 0.92804863]
 [-1.53718021]
 [ 1.20978907]
 [-1.11456955]
 [-0.83282911]
 [ 0.47022042]
 [ 0.25891509]
 [-0.86804666]
 [ 0.7167433 ]
 [-1.39630999]
 [-1.18500466]
 [-0.41021845]
 [ 0.47022042]
 [-0.12847801]
 [-0.48065356]
 [ 1.20978907]
 [ 0.78717841]
 [ 0.3293502 ]
 [-1.29065732]
 [-0.30456579]
 [ 0.29413264]
 [ 0.89283108]
 [ 0.99848374]
 [ 1.06891885]
 [-1.1497871 ]
 [ 0.36456775]
 [-1.53718021]
 [-1.1497871 ]
 [ 0.64630819]
 [ 1.49152951]
 [-0.12847801]
 [-1.60761532]
 [ 0.82239597]
 [-0.72717645]
 [-1.43152754]
 [ 0.92804863]
 [-0.90326422]
 [-1.22022221]
 [ 1.06891885]
 [-0.86804666]
 [-1.43152754]
 [ 0.50543797]
 [ 0.15326242]
 [ 0.89283108]
 [ 0.92804863]
 [-0.19891312]
 [ 1.31544173]
 [-0.12847801]
 [-0.23413068]
 [-1.43152754]
 [-0.41021845]
 [ 1.56196462]
 [ 1.28022418]
 [ 1.31544173]
 [-1.53718021]
 [-1.71326798]
 [-1.07935199]
 [-0.79761156]
 [-1.29065732]
 [ 1.35065929]
 [-1.25543977]
 [-0.51587112]
 [-1.53718021]
 [ 0.64630819]
 [ 0.61109064]
 [ 0.85761352]
 [-1.22022221]
 [-0.19891312]
 [-0.86804666]
 [ 1.1041364 ]
 [ 0.75196086]
 [ 1.52674706]
 [-0.30456579]
 [-1.29065732]
 [-1.4667451 ]
 [-1.1497871 ]
 [-0.02282535]
 [ 1.56196462]
 [-1.32587488]
 [ 0.22369753]
 [-0.58630623]
 [ 0.68152575]
 [-1.32587488]
 [-1.18500466]
 [-0.41021845]
 [ 1.13935396]
 [-0.55108867]
 [-0.33978334]
 [-0.48065356]
 [ 1.38587684]
 [ 0.29413264]
 [-1.64283287]
 [-0.3750009 ]
 [ 0.89283108]
 [-0.09326046]
 [-1.32587488]
 [-0.65674134]
 [-0.93848177]
 [ 1.20978907]
 [ 1.06891885]
 [ 1.56196462]
 [-0.16369557]
 [-1.11456955]
 [ 1.35065929]
 [ 1.13935396]
 [ 0.78717841]
 [-0.30456579]
 [ 0.61109064]
 [ 1.31544173]
 [-0.44543601]
 [-0.51587112]
 [ 1.52674706]
 [-0.12847801]
 [ 0.43500286]
 [-0.69195889]
 [-1.60761532]
 [-0.30456579]
 [-0.79761156]
 [-1.74848554]
 [ 1.63239973]
 [-1.57239776]
 [-0.69195889]
 [-1.43152754]
 [ 0.50543797]
 [ 1.31544173]
 [-0.55108867]
 [-1.57239776]
 [ 1.24500662]
 [ 0.64630819]
 [-0.09326046]
 [ 1.4210944 ]
 [ 1.70283484]
 [-0.762394  ]
 [-1.57239776]
 [ 1.73805239]
 [ 1.45631195]
 [-0.3750009 ]
 [-0.62152378]
 [-1.74848554]
 [ 1.73805239]
 [-1.22022221]
 [ 0.7167433 ]
 [ 1.56196462]
 [ 0.39978531]
 [ 1.38587684]
 [ 1.45631195]
 [-0.83282911]
 [-0.97369933]
 [ 1.70283484]
 [-1.04413444]
 [ 1.17457151]
 [ 1.56196462]
 [-1.50196265]
 [-1.60761532]
 [ 0.85761352]
 [-1.39630999]
 [ 0.75196086]
 [ 0.50543797]
 [-1.11456955]
 [-0.41021845]
 [ 0.78717841]
 [ 1.4210944 ]
 [-1.53718021]
 [-1.67805043]
 [ 0.08282732]
 [ 1.06891885]
 [-0.58630623]
 [ 0.36456775]
 [-0.02282535]
 [ 0.89283108]
 [ 1.31544173]
 [-0.41021845]
 [ 1.52674706]
 [-1.4667451 ]
 [-1.50196265]
 [ 1.13935396]
 [-1.4667451 ]
 [ 0.39978531]
 [ 0.89283108]
 [-1.39630999]
 [-1.71326798]
 [-1.39630999]
 [ 1.20978907]
 [-0.12847801]
 [ 0.18847998]
 [-1.4667451 ]
 [ 0.61109064]
 [ 1.49152951]
 [-0.3750009 ]
 [ 0.39978531]
 [ 0.82239597]
 [ 1.73805239]
 [-1.36109243]
 [-0.51587112]
 [-0.79761156]
 [-1.07935199]
 [-0.23413068]
 [-0.55108867]
 [ 0.68152575]
 [-0.62152378]
 [-0.69195889]
 [-1.71326798]
 [-0.16369557]
 [ 1.24500662]
 [ 0.61109064]
 [-1.43152754]
 [-1.36109243]
 [-1.60761532]
 [-0.19891312]
 [ 0.68152575]
 [-1.1497871 ]
 [-0.30456579]
 [ 1.66761728]
 [ 0.43500286]
 [-1.64283287]
 [-1.53718021]
 [ 1.52674706]
 [ 0.61109064]
 [-0.93848177]
 [-0.23413068]
 [ 0.99848374]
 [-1.71326798]
 [ 0.22369753]
 [ 0.78717841]
 [ 0.47022042]
 [-1.64283287]
 [-1.04413444]
 [-1.57239776]
 [ 0.43500286]
 [-1.22022221]
 [-0.3750009 ]
 [ 1.52674706]
 [ 0.92804863]
 [ 0.08282732]
 [-0.762394  ]
 [ 0.01239221]
 [-0.33978334]
 [-0.97369933]
 [-1.50196265]
 [ 0.7167433 ]
 [-1.60761532]
 [ 0.22369753]
 [ 1.35065929]
 [-1.60761532]
 [ 0.89283108]
 [ 0.61109064]
 [ 1.45631195]
 [ 0.57587308]
 [ 0.54065553]
 [ 1.1041364 ]
 [ 0.22369753]
 [-1.1497871 ]
 [-0.762394  ]
 [ 1.38587684]
 [-1.60761532]
 [ 0.68152575]
 [ 0.01239221]
 [ 1.4210944 ]
 [-1.50196265]
 [ 1.0337013 ]
 [ 0.61109064]
 [ 0.7167433 ]
 [ 0.57587308]
 [ 1.28022418]
 [-1.57239776]
 [ 0.36456775]
 [-0.30456579]
 [-0.02282535]
 [-0.86804666]
 [ 1.63239973]
 [ 0.22369753]
 [-0.16369557]
 [-1.57239776]
 [-0.55108867]
 [-1.43152754]
 [-1.50196265]
 [-0.48065356]
 [-1.04413444]
 [ 0.01239221]
 [ 0.78717841]
 [-0.02282535]
 [ 1.38587684]
 [ 0.85761352]
 [-0.65674134]
 [-1.71326798]
 [ 0.18847998]
 [ 1.56196462]
 [-1.1497871 ]
 [-0.09326046]
 [ 0.36456775]
 [ 1.31544173]
 [ 1.28022418]
 [-0.44543601]
 [-1.04413444]
 [-0.62152378]
 [-1.07935199]
 [ 1.28022418]
 [ 0.39978531]
 [ 1.24500662]
 [-0.55108867]
 [-0.55108867]
 [ 1.70283484]
 [-0.09326046]
 [-0.44543601]
 [ 0.15326242]
 [ 0.25891509]
 [-0.58630623]
 [-0.62152378]
 [ 1.73805239]
 [-1.57239776]
 [ 0.54065553]
 [ 0.64630819]
 [ 0.15326242]
 [-0.33978334]
 [ 0.39978531]
 [-1.67805043]
 [-1.57239776]
 [ 1.1041364 ]
 [ 0.22369753]
 [ 0.22369753]
 [ 0.3293502 ]
 [ 0.89283108]
 [ 0.50543797]
 [ 0.39978531]
 [ 1.06891885]
 [-0.79761156]
 [-1.25543977]
 [-0.33978334]
 [-0.23413068]
 [-1.04413444]
 [-0.79761156]
 [-1.50196265]
 [ 0.11804487]
 [-0.58630623]
 [-0.93848177]
 [-1.67805043]
 [ 0.75196086]
 [ 1.06891885]
 [-0.44543601]
 [ 1.0337013 ]
 [ 1.73805239]
 [-0.69195889]
 [ 1.17457151]
 [-0.58630623]
 [-1.39630999]
 [-0.0580429 ]
 [ 0.78717841]
 [-0.83282911]
 [ 0.36456775]
 [ 0.43500286]
 [ 0.47022042]
 [ 0.64630819]
 [ 0.15326242]
 [-0.72717645]
 [-1.74848554]
 [-0.62152378]
 [-0.09326046]
 [-1.50196265]
 [-0.69195889]
 [ 0.54065553]
 [ 0.01239221]
 [-0.72717645]
 [ 1.59718217]
 [-1.4667451 ]
 [-0.93848177]
 [-0.69195889]
 [ 0.43500286]
 [ 1.24500662]
 [-0.23413068]
 [-0.62152378]
 [-0.51587112]
 [-0.44543601]
 [ 0.29413264]
 [-1.64283287]
 [ 0.3293502 ]
 [-0.3750009 ]
 [ 0.15326242]
 [ 0.75196086]
 [ 1.70283484]
 [-0.69195889]
 [-0.93848177]
 [-1.53718021]
 [ 0.25891509]
 [ 1.52674706]
 [ 0.82239597]
 [-1.22022221]
 [-1.50196265]
 [-0.23413068]
 [-0.762394  ]
 [-0.26934823]
 [ 0.25891509]
 [ 0.50543797]
 [ 1.06891885]
 [-0.19891312]
 [-0.09326046]
 [ 0.89283108]
 [ 0.43500286]
 [-0.26934823]
 [-0.09326046]
 [-0.12847801]
 [-0.33978334]
 [-0.19891312]
 [-0.90326422]
 [ 1.56196462]
 [ 1.17457151]
 [ 0.43500286]
 [-1.4667451 ]
 [-0.55108867]
 [ 0.89283108]
 [-1.50196265]
 [ 1.28022418]
 [-0.23413068]
 [ 1.28022418]
 [-0.72717645]
 [ 0.68152575]
 [ 0.04760976]
 [ 0.15326242]
 [ 0.22369753]
 [-1.18500466]
 [ 0.47022042]
 [-0.90326422]
 [ 0.39978531]
 [-1.32587488]
 [-1.43152754]
 [-0.12847801]
 [-1.50196265]
 [-0.762394  ]
 [-1.71326798]
 [-0.55108867]
 [-0.23413068]
 [ 1.70283484]
 [-0.33978334]
 [ 0.15326242]
 [ 1.49152951]
 [ 1.28022418]
 [ 0.96326619]
 [-1.4667451 ]
 [ 1.24500662]
 [ 0.01239221]
 [-1.43152754]
 [-0.33978334]
 [-0.72717645]
 [-1.1497871 ]
 [ 0.43500286]
 [-1.07935199]
 [-0.33978334]
 [ 0.08282732]
 [-1.53718021]
 [-0.3750009 ]
 [-1.04413444]
 [ 1.63239973]
 [ 1.13935396]
 [-0.65674134]
 [ 0.99848374]
 [ 0.29413264]
 [ 1.1041364 ]
 [ 0.7167433 ]
 [ 1.45631195]
 [ 1.24500662]
 [-0.55108867]
 [-0.44543601]
 [ 0.75196086]
 [-0.93848177]
 [ 1.38587684]
 [ 1.06891885]
 [ 0.61109064]
 [-1.4667451 ]
 [ 0.89283108]
 [ 0.75196086]
 [-0.26934823]
 [-1.60761532]
 [-1.32587488]
 [ 0.68152575]
 [ 1.28022418]
 [ 1.35065929]
 [ 1.56196462]
 [ 0.43500286]
 [ 1.28022418]
 [-1.64283287]
 [ 0.3293502 ]
 [ 0.92804863]
 [-0.62152378]
 [-1.71326798]
 [ 0.29413264]
 [-0.86804666]
 [-0.86804666]
 [-0.33978334]
 [ 0.36456775]
 [ 1.66761728]
 [ 0.96326619]
 [-0.65674134]
 [ 1.20978907]
 [ 1.1041364 ]
 [-0.83282911]
 [ 0.47022042]
 [-0.23413068]
 [-0.33978334]
 [ 1.24500662]
 [-0.09326046]
 [-0.48065356]
 [ 0.18847998]
 [ 0.92804863]
 [-0.62152378]
 [ 1.20978907]
 [ 0.89283108]
 [ 0.54065553]
 [ 1.0337013 ]
 [ 0.61109064]
 [ 0.15326242]
 [ 0.18847998]
 [-1.04413444]
 [ 0.39978531]
 [ 0.61109064]
 [ 1.20978907]
 [-0.58630623]
 [-0.79761156]
 [ 0.36456775]
 [-0.58630623]
 [ 0.78717841]
 [-1.50196265]
 [-0.58630623]
 [-0.09326046]
 [ 1.35065929]
 [ 1.31544173]
 [-0.48065356]
 [ 1.0337013 ]
 [-0.16369557]
 [ 0.36456775]
 [-1.04413444]
 [-0.86804666]
 [ 0.50543797]
 [ 0.82239597]
 [ 1.31544173]
 [-0.86804666]
 [-1.1497871 ]
 [ 0.92804863]
 [-1.43152754]
 [-0.86804666]
 [-1.43152754]
 [-0.83282911]
 [-0.62152378]
 [-0.72717645]
 [-0.97369933]
 [-0.90326422]
 [ 0.61109064]
 [-0.48065356]
 [ 0.01239221]
 [-1.32587488]
 [-0.93848177]
 [-0.58630623]
 [ 0.75196086]
 [ 1.35065929]
 [-1.39630999]
 [ 1.35065929]
 [-1.29065732]
 [-0.09326046]
 [ 0.04760976]
 [ 0.96326619]
 [ 0.57587308]
 [ 0.29413264]
 [ 0.25891509]
 [-0.0580429 ]
 [-1.60761532]
 [ 0.47022042]
 [-0.762394  ]
 [-0.02282535]
 [ 1.56196462]
 [ 0.57587308]
 [ 1.20978907]
 [ 0.04760976]
 [-0.79761156]
 [-0.83282911]
 [-0.44543601]
 [ 1.17457151]
 [-1.74848554]
 [-1.43152754]
 [-1.64283287]
 [-1.11456955]
 [ 0.50543797]
 [ 0.47022042]
 [-1.50196265]
 [-1.60761532]
 [-0.33978334]
 [ 1.06891885]
 [ 1.63239973]
 [-0.02282535]
 [ 0.01239221]
 [ 1.24500662]
 [-1.4667451 ]
 [ 1.4210944 ]
 [ 1.38587684]
 [ 0.96326619]
 [-0.0580429 ]
 [ 0.54065553]
 [ 0.25891509]
 [ 1.59718217]
 [ 0.15326242]
 [ 1.06891885]
 [ 0.50543797]
 [-0.90326422]
 [ 0.43500286]
 [ 1.49152951]
 [ 1.31544173]
 [ 0.3293502 ]
 [ 1.17457151]
 [ 0.36456775]
 [-0.3750009 ]
 [ 1.4210944 ]
 [-0.12847801]
 [ 0.47022042]
 [-0.51587112]
 [ 1.4210944 ]
 [ 0.96326619]
 [-0.19891312]
 [-1.29065732]
 [-0.762394  ]
 [ 1.56196462]
 [ 0.22369753]
 [ 0.22369753]
 [-0.44543601]
 [-1.57239776]
 [ 1.70283484]
 [-0.65674134]
 [ 0.3293502 ]
 [ 1.70283484]
 [-1.57239776]
 [-0.26934823]
 [-0.16369557]
 [ 1.45631195]
 [ 0.18847998]
 [ 1.45631195]
 [-1.29065732]
 [ 0.54065553]
 [-0.33978334]
 [-0.79761156]
 [-0.30456579]
 [ 1.63239973]
 [ 0.08282732]
 [-0.65674134]
 [ 0.04760976]
 [-0.12847801]
 [-1.57239776]
 [-1.43152754]
 [-1.29065732]
 [-1.43152754]
 [ 0.22369753]
 [ 0.36456775]
 [ 0.11804487]
 [-0.58630623]
 [ 0.75196086]
 [-0.12847801]
 [ 0.18847998]
 [-0.55108867]
 [-1.18500466]
 [ 1.28022418]
 [ 1.20978907]
 [-1.11456955]
 [-0.0580429 ]
 [ 1.63239973]
 [-1.67805043]
 [ 1.4210944 ]
 [ 1.70283484]
 [ 0.29413264]
 [-0.51587112]
 [-0.02282535]
 [ 1.35065929]
 [ 0.39978531]
 [ 1.52674706]
 [-0.12847801]
 [-0.3750009 ]
 [-1.04413444]
 [ 0.57587308]
 [ 1.17457151]
 [-0.65674134]
 [-0.79761156]
 [-1.4667451 ]
 [ 1.4210944 ]
 [ 1.70283484]
 [-1.4667451 ]
 [ 0.50543797]
 [ 1.49152951]
 [ 1.49152951]
 [-1.11456955]
 [-0.33978334]
 [-1.39630999]
 [ 1.20978907]
 [ 1.73805239]
 [-0.83282911]
 [-0.65674134]
 [-0.44543601]
 [-0.19891312]
 [ 0.15326242]
 [ 1.63239973]
 [-0.30456579]
 [ 1.20978907]
 [-0.41021845]
 [-0.83282911]
 [ 0.92804863]
 [-0.97369933]
 [ 1.4210944 ]
 [ 1.13935396]
 [ 0.61109064]
 [ 0.04760976]
 [-0.58630623]
 [ 1.63239973]
 [ 1.45631195]
 [ 1.45631195]
 [ 1.20978907]
 [ 0.82239597]
 [ 0.36456775]
 [-0.16369557]
 [ 0.50543797]
 [ 0.75196086]
 [-0.62152378]
 [-0.65674134]
 [ 0.75196086]
 [ 0.11804487]
 [ 0.99848374]
 [-0.90326422]
 [ 1.17457151]
 [-0.41021845]
 [ 1.66761728]
 [ 0.96326619]
 [ 0.75196086]
 [-1.71326798]
 [-0.26934823]
 [-0.69195889]
 [ 0.08282732]
 [ 0.50543797]
 [-0.72717645]
 [ 0.08282732]
 [ 0.61109064]
 [ 1.31544173]
 [-0.62152378]
 [ 0.82239597]
 [ 1.20978907]
 [-1.53718021]
 [ 0.39978531]
 [ 0.82239597]
 [ 0.68152575]
 [-1.07935199]
 [ 0.61109064]
 [-1.11456955]
 [ 0.22369753]
 [-0.762394  ]
 [-0.58630623]
 [ 0.25891509]
 [ 1.24500662]
 [ 1.45631195]
 [ 1.56196462]
 [-0.51587112]
 [-0.97369933]
 [-1.74848554]
 [-0.16369557]
 [-1.32587488]
 [-0.41021845]
 [-0.58630623]
 [-0.12847801]
 [ 1.35065929]
 [-0.30456579]
 [ 1.0337013 ]
 [ 0.15326242]
 [ 0.36456775]
 [-1.32587488]
 [-1.74848554]
 [ 1.31544173]
 [ 1.63239973]
 [-0.51587112]
 [ 0.54065553]
 [-0.58630623]
 [ 0.01239221]
 [ 0.96326619]
 [-0.23413068]]

In [26]:
import numpy as np

In [37]:
print(np.sort(statistics.flatten()))

[-1.74848554 -1.74848554 -1.74848554 -1.74848554 -1.74848554 -1.74848554
 -1.71326798 -1.71326798 -1.71326798 -1.71326798 -1.71326798 -1.71326798
 -1.71326798 -1.71326798 -1.67805043 -1.67805043 -1.67805043 -1.67805043
 -1.64283287 -1.64283287 -1.64283287 -1.64283287 -1.64283287 -1.64283287
 -1.60761532 -1.60761532 -1.60761532 -1.60761532 -1.60761532 -1.60761532
 -1.60761532 -1.60761532 -1.60761532 -1.60761532 -1.57239776 -1.57239776
 -1.57239776 -1.57239776 -1.57239776 -1.57239776 -1.57239776 -1.57239776
 -1.57239776 -1.57239776 -1.57239776 -1.53718021 -1.53718021 -1.53718021
 -1.53718021 -1.53718021 -1.53718021 -1.53718021 -1.53718021 -1.53718021
 -1.50196265 -1.50196265 -1.50196265 -1.50196265 -1.50196265 -1.50196265
 -1.50196265 -1.50196265 -1.50196265 -1.50196265 -1.50196265 -1.50196265
 -1.4667451  -1.4667451  -1.4667451  -1.4667451  -1.4667451  -1.4667451
 -1.4667451  -1.4667451  -1.4667451  -1.4667451  -1.4667451  -1.43152754
 -1.43152754 -1.43152754 -1.43152754 -1.43152754 -1.43152754 -1.43152754
 -1.43152754 -1.43152754 -1.43152754 -1.43152754 -1.43152754 -1.43152754
 -1.39630999 -1.39630999 -1.39630999 -1.39630999 -1.39630999 -1.39630999
 -1.39630999 -1.36109243 -1.36109243 -1.32587488 -1.32587488 -1.32587488
 -1.32587488 -1.32587488 -1.32587488 -1.32587488 -1.32587488 -1.29065732
 -1.29065732 -1.29065732 -1.29065732 -1.29065732 -1.29065732 -1.29065732
 -1.25543977 -1.25543977 -1.22022221 -1.22022221 -1.22022221 -1.22022221
 -1.22022221 -1.18500466 -1.18500466 -1.18500466 -1.18500466 -1.1497871
 -1.1497871  -1.1497871  -1.1497871  -1.1497871  -1.1497871  -1.1497871
 -1.1497871  -1.11456955 -1.11456955 -1.11456955 -1.11456955 -1.11456955
 -1.11456955 -1.11456955 -1.07935199 -1.07935199 -1.07935199 -1.07935199
 -1.07935199 -1.04413444 -1.04413444 -1.04413444 -1.04413444 -1.04413444
 -1.04413444 -1.04413444 -1.04413444 -1.04413444 -0.97369933 -0.97369933
 -0.97369933 -0.97369933 -0.97369933 -0.93848177 -0.93848177 -0.93848177
 -0.93848177 -0.93848177 -0.93848177 -0.93848177 -0.90326422 -0.90326422
 -0.90326422 -0.90326422 -0.90326422 -0.90326422 -0.86804666 -0.86804666
 -0.86804666 -0.86804666 -0.86804666 -0.86804666 -0.86804666 -0.86804666
 -0.86804666 -0.83282911 -0.83282911 -0.83282911 -0.83282911 -0.83282911
 -0.83282911 -0.83282911 -0.83282911 -0.79761156 -0.79761156 -0.79761156
 -0.79761156 -0.79761156 -0.79761156 -0.79761156 -0.79761156 -0.79761156
 -0.762394   -0.762394   -0.762394   -0.762394   -0.762394   -0.762394
 -0.762394   -0.762394   -0.72717645 -0.72717645 -0.72717645 -0.72717645
 -0.72717645 -0.72717645 -0.72717645 -0.69195889 -0.69195889 -0.69195889
 -0.69195889 -0.69195889 -0.69195889 -0.69195889 -0.69195889 -0.65674134
 -0.65674134 -0.65674134 -0.65674134 -0.65674134 -0.65674134 -0.65674134
 -0.65674134 -0.65674134 -0.62152378 -0.62152378 -0.62152378 -0.62152378
 -0.62152378 -0.62152378 -0.62152378 -0.62152378 -0.62152378 -0.62152378
 -0.62152378 -0.58630623 -0.58630623 -0.58630623 -0.58630623 -0.58630623
 -0.58630623 -0.58630623 -0.58630623 -0.58630623 -0.58630623 -0.58630623
 -0.58630623 -0.58630623 -0.58630623 -0.55108867 -0.55108867 -0.55108867
 -0.55108867 -0.55108867 -0.55108867 -0.55108867 -0.55108867 -0.55108867
 -0.55108867 -0.51587112 -0.51587112 -0.51587112 -0.51587112 -0.51587112
 -0.51587112 -0.51587112 -0.51587112 -0.48065356 -0.48065356 -0.48065356
 -0.48065356 -0.48065356 -0.48065356 -0.44543601 -0.44543601 -0.44543601
 -0.44543601 -0.44543601 -0.44543601 -0.44543601 -0.44543601 -0.44543601
 -0.41021845 -0.41021845 -0.41021845 -0.41021845 -0.41021845 -0.41021845
 -0.41021845 -0.41021845 -0.3750009  -0.3750009  -0.3750009  -0.3750009
 -0.3750009  -0.3750009  -0.3750009  -0.3750009  -0.33978334 -0.33978334
 -0.33978334 -0.33978334 -0.33978334 -0.33978334 -0.33978334 -0.33978334
 -0.33978334 -0.33978334 -0.33978334 -0.33978334 -0.33978334 -0.30456579
 -0.30456579 -0.30456579 -0.30456579 -0.30456579 -0.30456579 -0.30456579
 -0.30456579 -0.30456579 -0.26934823 -0.26934823 -0.26934823 -0.26934823
 -0.26934823 -0.23413068 -0.23413068 -0.23413068 -0.23413068 -0.23413068
 -0.23413068 -0.23413068 -0.23413068 -0.23413068 -0.23413068 -0.19891312
 -0.19891312 -0.19891312 -0.19891312 -0.19891312 -0.19891312 -0.19891312
 -0.16369557 -0.16369557 -0.16369557 -0.16369557 -0.16369557 -0.16369557
 -0.16369557 -0.12847801 -0.12847801 -0.12847801 -0.12847801 -0.12847801
 -0.12847801 -0.12847801 -0.12847801 -0.12847801 -0.12847801 -0.12847801
 -0.12847801 -0.09326046 -0.09326046 -0.09326046 -0.09326046 -0.09326046
 -0.09326046 -0.09326046 -0.09326046 -0.09326046 -0.09326046 -0.0580429
 -0.0580429  -0.0580429  -0.0580429  -0.02282535 -0.02282535 -0.02282535
 -0.02282535 -0.02282535 -0.02282535 -0.02282535  0.01239221  0.01239221
  0.01239221  0.01239221  0.01239221  0.01239221  0.01239221  0.01239221
  0.04760976  0.04760976  0.04760976  0.04760976  0.04760976  0.08282732
  0.08282732  0.08282732  0.08282732  0.08282732  0.08282732  0.11804487
  0.11804487  0.11804487  0.15326242  0.15326242  0.15326242  0.15326242
  0.15326242  0.15326242  0.15326242  0.15326242  0.15326242  0.15326242
  0.15326242  0.18847998  0.18847998  0.18847998  0.18847998  0.18847998
  0.18847998  0.22369753  0.22369753  0.22369753  0.22369753  0.22369753
  0.22369753  0.22369753  0.22369753  0.22369753  0.22369753  0.22369753
  0.22369753  0.25891509  0.25891509  0.25891509  0.25891509  0.25891509
  0.25891509  0.25891509  0.29413264  0.29413264  0.29413264  0.29413264
  0.29413264  0.29413264  0.29413264  0.3293502   0.3293502   0.3293502
  0.3293502   0.3293502   0.3293502   0.36456775  0.36456775  0.36456775
  0.36456775  0.36456775  0.36456775  0.36456775  0.36456775  0.36456775
  0.36456775  0.36456775  0.36456775  0.39978531  0.39978531  0.39978531
  0.39978531  0.39978531  0.39978531  0.39978531  0.39978531  0.39978531
  0.39978531  0.43500286  0.43500286  0.43500286  0.43500286  0.43500286
  0.43500286  0.43500286  0.43500286  0.43500286  0.43500286  0.47022042
  0.47022042  0.47022042  0.47022042  0.47022042  0.47022042  0.47022042
  0.47022042  0.47022042  0.50543797  0.50543797  0.50543797  0.50543797
  0.50543797  0.50543797  0.50543797  0.50543797  0.50543797  0.50543797
  0.50543797  0.54065553  0.54065553  0.54065553  0.54065553  0.54065553
  0.54065553  0.54065553  0.57587308  0.57587308  0.57587308  0.57587308
  0.57587308  0.61109064  0.61109064  0.61109064  0.61109064  0.61109064
  0.61109064  0.61109064  0.61109064  0.61109064  0.61109064  0.61109064
  0.61109064  0.61109064  0.61109064  0.64630819  0.64630819  0.64630819
  0.64630819  0.64630819  0.68152575  0.68152575  0.68152575  0.68152575
  0.68152575  0.68152575  0.68152575  0.7167433   0.7167433   0.7167433
  0.7167433   0.7167433   0.75196086  0.75196086  0.75196086  0.75196086
  0.75196086  0.75196086  0.75196086  0.75196086  0.75196086  0.75196086
  0.75196086  0.78717841  0.78717841  0.78717841  0.78717841  0.78717841
  0.78717841  0.78717841  0.82239597  0.82239597  0.82239597  0.82239597
  0.82239597  0.82239597  0.82239597  0.85761352  0.85761352  0.85761352
  0.89283108  0.89283108  0.89283108  0.89283108  0.89283108  0.89283108
  0.89283108  0.89283108  0.89283108  0.89283108  0.89283108  0.92804863
  0.92804863  0.92804863  0.92804863  0.92804863  0.92804863  0.92804863
  0.92804863  0.96326619  0.96326619  0.96326619  0.96326619  0.96326619
  0.96326619  0.96326619  0.99848374  0.99848374  0.99848374  0.99848374
  1.0337013   1.0337013   1.0337013   1.0337013   1.0337013   1.06891885
  1.06891885  1.06891885  1.06891885  1.06891885  1.06891885  1.06891885
  1.06891885  1.06891885  1.06891885  1.1041364   1.1041364   1.1041364
  1.1041364   1.1041364   1.13935396  1.13935396  1.13935396  1.13935396
  1.13935396  1.17457151  1.17457151  1.17457151  1.17457151  1.17457151
  1.17457151  1.17457151  1.20978907  1.20978907  1.20978907  1.20978907
  1.20978907  1.20978907  1.20978907  1.20978907  1.20978907  1.20978907
  1.20978907  1.20978907  1.20978907  1.24500662  1.24500662  1.24500662
  1.24500662  1.24500662  1.24500662  1.24500662  1.24500662  1.24500662
  1.28022418  1.28022418  1.28022418  1.28022418  1.28022418  1.28022418
  1.28022418  1.28022418  1.28022418  1.28022418  1.31544173  1.31544173
  1.31544173  1.31544173  1.31544173  1.31544173  1.31544173  1.31544173
  1.31544173  1.31544173  1.31544173  1.35065929  1.35065929  1.35065929
  1.35065929  1.35065929  1.35065929  1.35065929  1.35065929  1.35065929
  1.38587684  1.38587684  1.38587684  1.38587684  1.38587684  1.38587684
  1.4210944   1.4210944   1.4210944   1.4210944   1.4210944   1.4210944
  1.4210944   1.4210944   1.4210944   1.45631195  1.45631195  1.45631195
  1.45631195  1.45631195  1.45631195  1.45631195  1.45631195  1.45631195
  1.49152951  1.49152951  1.49152951  1.49152951  1.49152951  1.49152951
  1.52674706  1.52674706  1.52674706  1.52674706  1.52674706  1.52674706
  1.52674706  1.56196462  1.56196462  1.56196462  1.56196462  1.56196462
  1.56196462  1.56196462  1.56196462  1.56196462  1.56196462  1.56196462
  1.59718217  1.59718217  1.63239973  1.63239973  1.63239973  1.63239973
  1.63239973  1.63239973  1.63239973  1.63239973  1.63239973  1.66761728
  1.66761728  1.66761728  1.70283484  1.70283484  1.70283484  1.70283484
  1.70283484  1.70283484  1.70283484  1.70283484  1.70283484  1.73805239
  1.73805239  1.73805239  1.73805239  1.73805239  1.73805239]

In [38]:
data2 = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.01.02-fish_weight_data.csv')
data2

     id  Length  Height  Width  FinSize  Weight
0     1   63.91   28.72   3.46    18.22  194.32
1     2   77.22   14.45   7.12    15.71  194.59
2     3   68.22   30.73   4.09     7.33  191.24
3     4   63.59   38.68   2.21     2.54  194.23
4     5   53.89   13.71   0.73     8.74  131.82
..  ...     ...     ...    ...      ...     ...
95   96   34.66   22.17   2.63    19.22  124.89
96   97   66.92   12.96   1.43     7.75  152.90
97   98   21.61   13.90   8.69     7.78   77.97
98   99   86.32    7.03   9.74     1.31  193.44
99  100   20.38   20.20   9.63     4.52   80.69

[100 rows x 6 columns]

In [39]:
data2.isnull().sum()

id         0
Length     0
Height     0
Width      0
FinSize    0
Weight     0
dtype: int64

In [40]:
data2.corr()

               id    Length    Height     Width   FinSize    Weight
id       1.000000 -0.252937 -0.197469  0.116863  0.175485 -0.273700
Length  -0.252937  1.000000 -0.066048 -0.036361  0.021882  0.947420
Height  -0.197469 -0.066048  1.000000 -0.124041 -0.062081  0.222426
Width    0.116863 -0.036361 -0.124041  1.000000 -0.114974 -0.046809
FinSize  0.175485  0.021882 -0.062081 -0.114974  1.000000  0.107433
Weight  -0.273700  0.947420  0.222426 -0.046809  0.107433  1.000000

In [42]:
data1_3 = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.01.03-apartment_prices_dataset.csv')
data1_3

,Size,Bedrooms,Bathrooms,Floor,Age,DistanceToCenter,NearbySchools,NearbyParks,PublicTransport,SafetyIndex,Price
0,132.322026,2,2,12,23,5.916263,7.0,1.0,5.0,54,204546.3152
1,157.278405,2,2,16,1,4.765030,9.0,4.0,5.0,44,224020.0640
2,131.732477,1,1,18,18,16.529690,1.0,2.0,3.0,94,110609.5388
3,113.548220,3,1,13,43,15.602367,3.0,1.0,4.0,75,143313.9356
4,146.884117,2,1,13,7,9.115029,6.0,3.0,1.0,89,162672.0736
...,...,...,...,...,...,...,...,...,...,...,...
730,126.029444,2,1,19,4,17.934586,1.0,2.0,6.0,22,108861.0303
731,160.527974,4,2,15,12,12.577909,0.0,1.0,9.0,66,197467.8326
732,190.761803,3,2,11,2,13.684781,0.0,1.0,5.0,24,208670.7676
733,84.296983,1,1,7,7,4.711033,8.0,0.0,8.0,72,176553.5646
734,151.571172,2,1,10,47,14.911264,9.0,3.0,5.0,26,171480.0825

In [43]:
data1_3.isnull().sum()

Size                0
Bedrooms            0
Bathrooms           0
Floor               0
Age                 0
DistanceToCenter    0
NearbySchools       0
NearbyParks         0
PublicTransport     0
SafetyIndex         0
Price               0
dtype: int64

In [46]:
data1_3.describe()

,Size,Bedrooms,Bathrooms,Floor,Age,DistanceToCenter,NearbySchools,NearbyParks,PublicTransport,SafetyIndex,Price
count,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000
mean,124.582571,2.571429,1.489796,9.840816,26.025850,10.016021,4.448667,2.049735,5.195673,51.990476,177596.078874
std,47.019547,1.228632,0.529348,5.998226,17.277685,5.481185,3.176804,1.487053,3.001572,30.749470,38169.195283
min,21.205359,0.000000,0.000000,0.000000,0.000000,0.313919,0.000000,0.000000,0.332843,0.000000,72251.280230
25%,87.131283,2.000000,1.000000,5.000000,12.000000,5.337026,2.000000,1.000000,3.000000,25.500000,150768.426850
50%,121.907682,3.000000,1.000000,10.000000,25.000000,9.844233,4.000000,2.000000,5.000000,52.000000,177234.288600
75%,160.456029,4.000000,2.000000,15.000000,38.000000,14.574648,7.000000,3.000000,7.000000,78.000000,203350.413500
max,563.615954,11.000000,5.000000,54.000000,130.000000,38.124819,26.897485,11.642260,25.884225,260.000000,280053.787600

In [47]:
data1_3.isnull().sum()

Size                0
Bedrooms            0
Bathrooms           0
Floor               0
Age                 0
DistanceToCenter    0
NearbySchools       0
NearbyParks         0
PublicTransport     0
SafetyIndex         0
Price               0
dtype: int64

In [52]:
cols =data1_3.columns
cols

Index(['Size', 'Bedrooms', 'Bathrooms', 'Floor', 'Age', 'DistanceToCenter',
       'NearbySchools', 'NearbyParks', 'PublicTransport', 'SafetyIndex',
       'Price'],
      dtype='object')

In [57]:
var_count = {}

for col in cols:
  q1, q3 = data1_3[col].quantile([0.25, 0.75])
  iqr = q3 - q1
  count = (((data1_3[col]) < (q1 - 1.5*iqr)) | ((data1_3[col]) > (q3 + 1.5*iqr))).sum()
  var_count[col] = count

print(var_count)

{'Size': np.int64(1), 'Bedrooms': np.int64(3), 'Bathrooms': np.int64(2), 'Floor': np.int64(4), 'Age': np.int64(15), 'DistanceToCenter': np.int64(1), 'NearbySchools': np.int64(5), 'NearbyParks': np.int64(4), 'PublicTransport': np.int64(5), 'SafetyIndex': np.int64(3), 'Price': np.int64(0)}

In [61]:
sorted_var_count = sorted(
    var_count.items(),
    key=lambda x: x[1],
    reverse=True
)

print(sorted_var_count)

[('Age', np.int64(15)), ('NearbySchools', np.int64(5)), ('PublicTransport', np.int64(5)), ('Floor', np.int64(4)), ('NearbyParks', np.int64(4)), ('Bedrooms', np.int64(3)), ('SafetyIndex', np.int64(3)), ('Bathrooms', np.int64(2)), ('Size', np.int64(1)), ('DistanceToCenter', np.int64(1)), ('Price', np.int64(0))]

In [62]:
train = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.02.01-sales_train_dataset.csv')
test = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.02.02-sales_test_dataset_x.csv')
test_y = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.02.03-sales_test_dataset_y.csv')

In [71]:
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   BranchName                700 non-null    object
 1   City                      700 non-null    object
 2   Population                700 non-null    int64
 3   IncomeGeneratingPopRatio  700 non-null    float64
 4   AverageIncome             700 non-null    int64
 5   IndustryType              700 non-null    object
 6   Sales                     700 non-null    int64
dtypes: float64(1), int64(3), object(3)
memory usage: 38.4+ KB
None

In [64]:
print(test)

    BranchName City  Population  IncomeGeneratingPopRatio  AverageIncome  \
0        지점994   수원     2620192                  0.272974        3971748
1        지점860   부산     1633511                  0.208515        6905129
2        지점299   광주     1511031                  0.552322        4664242
3        지점554   울산     2165618                  0.359201        4085372
4        지점673   울산      668309                  0.661939        6903510
..         ...  ...         ...                       ...            ...
295      지점168   광주     1313450                  0.289100        3541481
296      지점999   부산      873247                  0.542756        3712469
297      지점985   수원      798258                  0.459549        5151208
298      지점492   대구      661475                  0.436693        6201716
299       지점11   수원     2133960                  0.226765        6428867

    IndustryType
0            제조업
1            제조업
2             농업
3           서비스업
4            제조업
..           ...
295           농업
296           농업
297           농업
298         서비스업
299          제조업

[300 rows x 6 columns]

In [68]:
print(train.columns)
print(test.columns)

Index(['BranchName', 'City', 'Population', 'IncomeGeneratingPopRatio',
       'AverageIncome', 'IndustryType', 'Sales'],
      dtype='object')
Index(['BranchName', 'City', 'Population', 'IncomeGeneratingPopRatio',
       'AverageIncome', 'IndustryType'],
      dtype='object')

In [69]:
print(train.isnull().sum())
print()
print(test.isnull().sum())

BranchName                  0
City                        0
Population                  0
IncomeGeneratingPopRatio    0
AverageIncome               0
IndustryType                0
Sales                       0
dtype: int64

BranchName                  0
City                        0
Population                  0
IncomeGeneratingPopRatio    0
AverageIncome               0
IndustryType                0
dtype: int64

In [72]:
import pandas as pd

In [84]:
data1 = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.01.01-students_scores.csv')
data1

     student id  Statistics  DataScience  MachineLearning  EnglishLiterature
0             1         NaN         54.0             94.0               62.0
1             2        76.0         16.0             80.0                NaN
2             3         6.0          NaN             68.0               45.0
3             4        84.0         30.0             76.0                NaN
4             5         NaN         53.0             33.0               90.0
..          ...         ...          ...              ...                ...
995         996        33.0          3.0              NaN               86.0
996         997        50.0         33.0              3.0                NaN
997         998        77.0         34.0             79.0                NaN
998         999        43.0         97.0             30.0                NaN
999        1000         NaN         41.0             28.0                9.0

[1000 rows x 5 columns]

In [88]:
(data1.isnull().sum()).sort_values(ascending = True)

student id             0
Statistics           227
MachineLearning      231
EnglishLiterature    251
DataScience          291
dtype: int64

In [90]:
st_data = data1['Statistics'].dropna()
st_data.isnull().sum()

np.int64(0)

In [92]:
from sklearn.preprocessing import StandardScaler

In [99]:
s_scaler = StandardScaler()
st_dataf = pd.DataFrame(st_data)
sc_df= s_scaler.fit_transform(st_dataf)

In [103]:
round(sc_df.max(),2)

np.float64(1.74)

In [104]:
data2 = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.01.02-fish_weight_data.csv')
data2

     id  Length  Height  Width  FinSize  Weight
0     1   63.91   28.72   3.46    18.22  194.32
1     2   77.22   14.45   7.12    15.71  194.59
2     3   68.22   30.73   4.09     7.33  191.24
3     4   63.59   38.68   2.21     2.54  194.23
4     5   53.89   13.71   0.73     8.74  131.82
..  ...     ...     ...    ...      ...     ...
95   96   34.66   22.17   2.63    19.22  124.89
96   97   66.92   12.96   1.43     7.75  152.90
97   98   21.61   13.90   8.69     7.78   77.97
98   99   86.32    7.03   9.74     1.31  193.44
99  100   20.38   20.20   9.63     4.52   80.69

[100 rows x 6 columns]

In [106]:
data2 = data2.drop('id' ,axis = 1)

In [108]:
data2

    Length  Height  Width  FinSize  Weight
0    63.91   28.72   3.46    18.22  194.32
1    77.22   14.45   7.12    15.71  194.59
2    68.22   30.73   4.09     7.33  191.24
3    63.59   38.68   2.21     2.54  194.23
4    53.89   13.71   0.73     8.74  131.82
..     ...     ...    ...      ...     ...
95   34.66   22.17   2.63    19.22  124.89
96   66.92   12.96   1.43     7.75  152.90
97   21.61   13.90   8.69     7.78   77.97
98   86.32    7.03   9.74     1.31  193.44
99   20.38   20.20   9.63     4.52   80.69

[100 rows x 5 columns]

In [110]:
df_corr = data2.corr()

In [111]:
corr1 = df_corr['Weight'].drop('Weight')

In [116]:
corr1.abs().idxmax()

'Length'

In [124]:
data3 = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.01.03-apartment_prices_dataset.csv')
data3

,Size,Bedrooms,Bathrooms,Floor,Age,DistanceToCenter,NearbySchools,NearbyParks,PublicTransport,SafetyIndex,Price
0,132.322026,2,2,12,23,5.916263,7.0,1.0,5.0,54,204546.3152
1,157.278405,2,2,16,1,4.765030,9.0,4.0,5.0,44,224020.0640
2,131.732477,1,1,18,18,16.529690,1.0,2.0,3.0,94,110609.5388
3,113.548220,3,1,13,43,15.602367,3.0,1.0,4.0,75,143313.9356
4,146.884117,2,1,13,7,9.115029,6.0,3.0,1.0,89,162672.0736
...,...,...,...,...,...,...,...,...,...,...,...
730,126.029444,2,1,19,4,17.934586,1.0,2.0,6.0,22,108861.0303
731,160.527974,4,2,15,12,12.577909,0.0,1.0,9.0,66,197467.8326
732,190.761803,3,2,11,2,13.684781,0.0,1.0,5.0,24,208670.7676
733,84.296983,1,1,7,7,4.711033,8.0,0.0,8.0,72,176553.5646
734,151.571172,2,1,10,47,14.911264,9.0,3.0,5.0,26,171480.0825

In [125]:
data3 = data3.drop('Price', axis=1)
cols = data3.columns
print(cols)

Index(['Size', 'Bedrooms', 'Bathrooms', 'Floor', 'Age', 'DistanceToCenter',
       'NearbySchools', 'NearbyParks', 'PublicTransport', 'SafetyIndex'],
      dtype='object')

In [136]:
var_counts = {}

for col in cols:
  q1 = data3[col].quantile(0.25)
  q3 = data3[col].quantile(0.75)
  iqr = q3-q1
  var_counts[col] = (((data3[col]) < (q1 - 1.5*iqr))|((data3[col]) > (q3 + 1.5*iqr))).sum()

print(var_counts)

{'Size': np.int64(1), 'Bedrooms': np.int64(3), 'Bathrooms': np.int64(2), 'Floor': np.int64(4), 'Age': np.int64(15), 'DistanceToCenter': np.int64(1), 'NearbySchools': np.int64(5), 'NearbyParks': np.int64(4), 'PublicTransport': np.int64(5), 'SafetyIndex': np.int64(3)}

In [137]:
sorted(var_counts.items(), key=lambda x: x[1], reverse=True)

[('Age', np.int64(15)),
 ('NearbySchools', np.int64(5)),
 ('PublicTransport', np.int64(5)),
 ('Floor', np.int64(4)),
 ('NearbyParks', np.int64(4)),
 ('Bedrooms', np.int64(3)),
 ('SafetyIndex', np.int64(3)),
 ('Bathrooms', np.int64(2)),
 ('Size', np.int64(1)),
 ('DistanceToCenter', np.int64(1))]

In [138]:
train = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.02.01-sales_train_dataset.csv')
test = pd.read_csv('/content/yemoonsaBigdata/datasets/Part5/ex7/07.02.02-sales_test_dataset_x.csv')

In [139]:
print(train.info())
print()
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   BranchName                700 non-null    object
 1   City                      700 non-null    object
 2   Population                700 non-null    int64
 3   IncomeGeneratingPopRatio  700 non-null    float64
 4   AverageIncome             700 non-null    int64
 5   IndustryType              700 non-null    object
 6   Sales                     700 non-null    int64
dtypes: float64(1), int64(3), object(3)
memory usage: 38.4+ KB
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   BranchName                700 non-null    object
 1   City                      700 non-null    object
 2   Population                700 non-null    int64
 3   IncomeGeneratingPopRatio  700 non-null    float64
 4   AverageIncome             700 non-null    int64
 5   IndustryType              700 non-null    object
 6   Sales                     700 non-null    int64
dtypes: float64(1), int64(3), object(3)
memory usage: 38.4+ KB
None

In [143]:
x = train.drop('Sales', axis = 1)
y = train['Sales']
print(train.shape)
print(x.shape)
print(y.shape)

(700, 7)
(700, 6)
(700,)