In [15]:
import pandas as pd

In [26]:
data = pd.read_excel('통합_1.xlsx')
data

            날짜  지역    주택구입부담지수  기준금리    거래량      인구수    물가지수  주택인허가실적  실거래가격지수
0   2021-01-01  서울  163.970000  0.50  12275  9657969  100.86     2695    167.6
1   2021-02-01  서울  166.200000  0.50  12707  9648606  101.33     9599    169.9
2   2021-03-01  서울  168.430000  0.50  11122  9598484  101.57    16290    170.8
3   2021-04-01  서울  169.870000  0.50  11873  9588711  101.68    26397    171.9
4   2021-05-01  서울  172.900000  0.50  13145  9575355  101.74    30915    175.4
..         ...  ..         ...   ...    ...      ...     ...      ...      ...
811 2024-08-01  제주   72.300000  3.50    532   671540  114.25     2028    109.4
812 2024-09-01  제주   73.827162  3.50    485   671064  114.09     2254    109.7
813 2024-10-01  제주   76.002123  3.25    614   670837  114.34     2456    111.4
814 2024-11-01  제주   75.600000  3.00    557   670632  114.11     2557    109.7
815 2024-12-01  제주   75.197877  3.00    534   670368  114.37     3264    107.0

[816 rows x 9 columns]

패널 회귀분석 (고정)

In [38]:
from linearmodels.panel import PanelOLS
from linearmodels.panel import compare
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
import numpy as np

In [27]:
data.isna().count()

날짜          816
지역          816
주택구입부담지수    816
기준금리        816
거래량         816
인구수         816
물가지수        816
주택인허가실적     816
실거래가격지수     816
dtype: int64

In [28]:
data['날짜'] = pd.to_datetime(data['날짜'])
data

            날짜  지역    주택구입부담지수  기준금리    거래량      인구수    물가지수  주택인허가실적  실거래가격지수
0   2021-01-01  서울  163.970000  0.50  12275  9657969  100.86     2695    167.6
1   2021-02-01  서울  166.200000  0.50  12707  9648606  101.33     9599    169.9
2   2021-03-01  서울  168.430000  0.50  11122  9598484  101.57    16290    170.8
3   2021-04-01  서울  169.870000  0.50  11873  9588711  101.68    26397    171.9
4   2021-05-01  서울  172.900000  0.50  13145  9575355  101.74    30915    175.4
..         ...  ..         ...   ...    ...      ...     ...      ...      ...
811 2024-08-01  제주   72.300000  3.50    532   671540  114.25     2028    109.4
812 2024-09-01  제주   73.827162  3.50    485   671064  114.09     2254    109.7
813 2024-10-01  제주   76.002123  3.25    614   670837  114.34     2456    111.4
814 2024-11-01  제주   75.600000  3.00    557   670632  114.11     2557    109.7
815 2024-12-01  제주   75.197877  3.00    534   670368  114.37     3264    107.0

[816 rows x 9 columns]

In [29]:
data = data.set_index(['지역','날짜'])
y = data['실거래가격지수']
x = data[['주택구입부담지수', '기준금리', '거래량', '인구수', '물가지수', '주택인허가실적']]

In [31]:
x = sm.add_constant(x)

In [34]:
model = PanelOLS(y,x, entity_effects=True)
results = model.fit()
print(results.summary)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                실거래가격지수   R-squared:                        0.6555
Estimator:                   PanelOLS   R-squared (Between):              0.6459
No. Observations:                 816   R-squared (Within):               0.6555
Date:                Sun, Nov 02 2025   R-squared (Overall):              0.6475
Time:                        21:30:47   Log-likelihood                   -2495.0
Cov. Estimator:            Unadjusted
                                        F-statistic:                      251.44
Entities:                          17   P-value                           0.0000
Avg Obs:                       48.000   Distribution:                   F(6,793)
Min Obs:                       48.000
Max Obs:                       48.000   F-statistic (robust):             251.44
                                        P-value                           0.0000
Time periods:                      48   Distribution:                   F(6,793)
Avg Obs:                       17.000
Min Obs:                       17.000
Max Obs:                       17.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const         -73.554     24.350    -3.0207     0.0026     -121.35     -25.756
주택구입부담지수       0.5947     0.0224     26.569     0.0000      0.5508      0.6387
기준금리          -7.3631     0.4646    -15.848     0.0000     -8.2750     -6.4511
거래량            0.0007     0.0001     5.6103     0.0000      0.0005      0.0010
인구수         1.825e-07  6.324e-06     0.0289     0.9770  -1.223e-05    1.26e-05
물가지수           1.5495     0.1227     12.625     0.0000      1.3086      1.7904
주택인허가실적     3.443e-05  1.445e-05     2.3821     0.0174   6.058e-06    6.28e-05
==============================================================================

F-test for Poolability: 180.52
P-value: 0.0000
Distribution: F(16,793)

Included effects: Entity

In [39]:
y_pred = results.fitted_values
rmse = np.sqrt(mean_squared_error(y, y_pred))
print(f"\nRMSE: {rmse:.4f}")

RMSE: 12.5872

패널 회귀분석(랜덤)

In [42]:
from linearmodels.panel import RandomEffects

data = pd.read_excel('통합_1.xlsx')
data = data.set_index(['지역','날짜'])
y = data['실거래가격지수']
x = data[['주택구입부담지수', '기준금리', '거래량', '인구수', '물가지수', '주택인허가실적']]
x = sm.add_constant(x)
model = RandomEffects(y,x)
results = model.fit()
print(results.summary)

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:                실거래가격지수   R-squared:                        0.6560
Estimator:              RandomEffects   R-squared (Between):              0.6922
No. Observations:                 816   R-squared (Within):               0.6554
Date:                Sun, Nov 02 2025   R-squared (Overall):              0.6859
Time:                        21:39:15   Log-likelihood                   -2501.6
Cov. Estimator:            Unadjusted
                                        F-statistic:                      257.18
Entities:                          17   P-value                           0.0000
Avg Obs:                       48.000   Distribution:                   F(6,809)
Min Obs:                       48.000
Max Obs:                       48.000   F-statistic (robust):             257.18
                                        P-value                           0.0000
Time periods:                      48   Distribution:                   F(6,809)
Avg Obs:                       17.000
Min Obs:                       17.000
Max Obs:                       17.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const         -68.794     13.218    -5.2044     0.0000     -94.740     -42.847
주택구입부담지수       0.5872     0.0217     27.091     0.0000      0.5446      0.6297
기준금리          -7.3726     0.4629    -15.928     0.0000     -8.2812     -6.4641
거래량            0.0007     0.0001     5.6348     0.0000      0.0005      0.0009
인구수         -9.33e-07  9.249e-07    -1.0088     0.3134  -2.748e-06   8.825e-07
물가지수           1.5419     0.1218     12.661     0.0000      1.3029      1.7810
주택인허가실적     3.583e-05  1.439e-05     2.4893     0.0130   7.577e-06   6.408e-05
==============================================================================

In [43]:
y_pred = results.fitted_values
rmse = np.sqrt(mean_squared_error(y, y_pred))
print(f"\nRMSE: {rmse:.4f}")

RMSE: 11.8822