In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('통합.xlsx')
data

            날짜  지역    주택구입부담지수  기준금리    거래량      인구수    물가지수
0   2021-01-01  서울  163.970000  0.50  12275  9657969  100.86
1   2021-02-01  서울  166.200000  0.50  12707  9648606  101.33
2   2021-03-01  서울  168.430000  0.50  11122  9598484  101.57
3   2021-04-01  서울  169.870000  0.50  11873  9588711  101.68
4   2021-05-01  서울  172.900000  0.50  13145  9575355  101.74
..         ...  ..         ...   ...    ...      ...     ...
811 2024-08-01  제주   72.300000  3.50    532   671540  114.25
812 2024-09-01  제주   73.827162  3.50    485   671064  114.09
813 2024-10-01  제주   76.002123  3.25    614   670837  114.34
814 2024-11-01  제주   75.600000  3.00    557   670632  114.11
815 2024-12-01  제주   75.197877  3.00    534   670368  114.37

[816 rows x 7 columns]

In [8]:
data['지역'].unique()

array(['서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종', '경기', '강원', '충북',
       '충남', '전북', '전남', '경북', '경남', '제주'], dtype=object)

In [67]:
data1 = pd.read_excel('capstone/아파트 매매 실거래가격지수_31233316.xlsx')
data1

,계정항목,2021/01,2021/02,2021/03,2021/04,2021/05,2021/06,2021/07,2021/08,2021/09,...,2024/03,2024/04,2024/05,2024/06,2024/07,2024/08,2024/09,2024/10,2024/11,2024/12
0,전국,123.6,125.8,127.5,129.2,131.5,134.5,137.8,141.1,143.8,...,123.0,122.9,122.9,123.5,124.5,125.2,125.5,125.4,124.9,124.2
1,서울,167.6,169.9,170.8,171.9,175.4,179.7,183.7,187.2,190.1,...,159.8,160.9,162.1,164.5,168.1,170.8,171.3,171.3,171.4,170.6
2,도심권,157.7,159.0,158.9,161.5,163.6,169.0,170.9,174.9,175.7,...,166.8,167.0,169.6,170.9,173.9,178.2,178.3,178.2,177.0,176.5
3,동북권,177.0,180.5,182.0,183.6,187.1,191.2,195.9,198.8,202.2,...,162.2,163.1,164.1,165.9,169.3,171.5,171.3,171.3,171.3,169.6
4,동남권,162.7,164.1,164.1,164.8,167.8,171.8,176.1,180.1,183.2,...,160.0,161.1,163.0,166.4,171.1,174.8,176.4,176.7,177.6,177.2
5,서북권,164.6,166.9,166.1,168.9,169.0,174.8,178.3,180.9,183.8,...,156.2,157.2,158.3,160.7,163.8,166.9,166.3,166.7,166.3,165.6
6,서남권,165.1,167.2,168.2,169.3,173.7,177.0,180.3,184.9,187.6,...,158.4,159.8,160.5,162.9,166.1,168.0,168.8,168.2,168.3,167.9
7,수도권,141.1,144.6,147.2,149.6,153.5,158.3,163.3,168.4,172.3,...,141.9,142.4,142.8,144.1,146.0,147.7,147.9,147.9,147.3,146.5
8,지방,108.4,109.7,110.6,111.6,112.7,114.2,115.9,117.7,119.5,...,107.3,106.8,106.4,106.4,106.6,106.6,106.8,106.7,106.2,105.7
9,부산,112.2,113.8,114.0,115.8,117.6,119.7,122.2,123.8,124.7,...,105.1,104.5,104.1,103.9,104.0,104.2,104.1,103.9,103.5,102.9
10,대구,127.1,129.0,130.4,130.6,131.2,131.8,132.8,132.6,132.5,...,100.6,100.2,100.0,99.5,99.6,99.1,99.3,99.1,99.0,98.1
11,인천,115.3,118.1,121.5,124.8,129.4,134.8,141.0,147.3,151.9,...,122.0,121.8,121.9,122.8,123.7,124.4,124.4,124.3,123.5,122.9
12,광주,120.5,121.9,122.2,123.1,123.6,125.7,127.8,130.7,134.9,...,125.1,123.7,123.3,122.9,123.1,123.4,123.9,123.1,121.9,121.7
13,대전,144.3,146.2,148.6,150.9,152.3,156.4,158.7,162.3,165.0,...,142.0,141.6,141.3,140.8,141.2,141.0,141.0,141.8,140.6,140.0
14,울산,103.3,103.8,104.3,105.4,105.5,106.4,108.1,108.8,110.1,...,99.5,99.6,99.2,99.6,99.4,99.7,100.1,100.8,100.6,100.6
15,세종,170.6,174.1,174.1,170.4,173.9,174.4,170.2,169.3,170.8,...,129.7,128.9,127.9,128.7,129.2,129.9,129.3,129.0,128.8,125.7
16,경기,132.1,136.4,140.0,143.1,147.0,152.0,157.5,163.3,167.5,...,137.4,137.7,137.7,138.6,139.8,141.1,141.2,141.2,140.4,139.4
17,강원,95.7,96.8,98.2,99.4,100.1,101.6,103.8,105.4,108.2,...,111.6,111.1,111.1,110.7,110.9,111.4,111.6,111.3,110.4,111.0
18,충북,95.6,97.6,99.2,100.5,102.5,104.3,106.0,109.0,111.3,...,109.3,109.2,108.2,109.1,109.5,109.4,109.8,109.5,109.0,108.0
19,충남,99.3,100.1,101.6,102.3,103.4,104.9,106.3,109.1,111.6,...,104.7,104.6,104.8,104.4,104.9,104.5,104.9,105.1,104.1,104.0
20,전북,99.6,100.4,102.2,103.1,104.5,106.5,108.6,111.2,113.7,...,109.3,109.0,108.8,109.0,108.8,109.8,110.8,110.5,110.2,110.2
21,전남,108.6,109.1,109.7,110.0,110.3,111.1,111.0,112.1,114.1,...,106.9,106.4,106.0,106.1,106.6,106.1,105.7,106.3,105.4,105.6
22,경북,95.8,97.3,97.8,99.1,99.7,100.4,102.0,103.9,105.1,...,100.6,99.7,98.9,100.0,99.7,99.9,100.6,99.9,99.4,98.6
23,경남,94.0,94.5,95.0,95.6,97.0,97.9,99.4,101.3,103.3,...,96.5,96.2,95.9,95.6,96.0,95.4,95.7,95.5,95.5,94.7
24,제주,95.6,97.1,99.9,100.1,102.5,103.2,106.8,109.5,113.4,...,108.2,110.3,106.7,109.7,109.4,109.4,109.7,111.4,109.7,107.0
25,광역시 1),118.1,119.8,121.1,122.8,124.5,127.0,129.9,132.3,134.5,...,112.9,112.4,112.1,112.1,112.4,112.6,112.6,112.6,112.0,111.5
26,지방광역시 2),118.8,120.3,121.1,122.3,123.4,125.3,127.3,128.8,130.4,...,110.8,110.2,109.9,109.6,109.7,109.8,109.9,109.9,109.3,108.8
27,지방도 3),97.7,98.7,99.8,100.7,101.8,103.0,104.6,106.7,108.9,...,104.4,104.1,103.6,103.8,104.0,104.0,104.4,104.3,103.7,103.3

In [68]:
data2 = pd.read_excel('capstone/주택건설인허가실적_31233443.xlsx')
data2

,계정항목,2021/01,2021/02,2021/03,2021/04,2021/05,2021/06,2021/07,2021/08,2021/09,...,2024/03,2024/04,2024/05,2024/06,2024/07,2024/08,2024/09,2024/10,2024/11,2024/12
0,전국,26183,59830,105184,149793,186743,230761,277354,312860,358990,...,74558,102482,125974,149860,171677,200155,218641,244777,273121,428244
1,서울,2695,9599,16290,26397,30915,37194,46041,50638,62516,...,6493,7159,10530,13174,16549,22348,24140,27095,33716,45975
2,인천,1327,2029,2430,2855,3546,3962,5119,6970,7480,...,2391,3868,5627,6296,6582,8730,9028,12396,12624,20399
3,경기,8141,19110,34085,49040,59683,75883,91980,105456,113873,...,21422,30556,35106,40791,46336,54578,57412,62780,69218,160983
4,부산,2256,3193,4330,5809,8479,9891,13936,14111,15166,...,2207,6138,10265,11737,16581,18742,18750,23193,24955,29196
5,대구,308,1743,6997,8740,9515,10227,12215,13589,16795,...,1264,1286,1309,1340,1358,2295,2312,2328,3217,3227
6,광주,57,495,930,1176,1802,2034,3548,3645,3880,...,801,1226,1253,1364,3125,3603,3674,3679,3904,5443
7,대전,884,3446,7026,7196,8461,8596,8898,9215,9449,...,10297,12369,13251,13282,14456,14608,18063,21542,22371,28325
8,울산,2200,2251,3606,4026,4159,4561,4863,5019,6180,...,1128,1890,2474,2493,3062,3088,3202,3468,3492,4122
9,세종,15,38,75,118,1537,1946,2000,2092,2116,...,1267,3354,3363,3370,3376,3406,3438,3448,3485,9023
10,강원,393,768,1276,2719,4942,7096,9509,10118,10560,...,2563,3359,3900,6416,6662,8469,9060,10860,12543,13631
11,충북,3138,4038,4652,5115,5469,7652,8100,8382,12946,...,3364,4535,5327,7557,8299,9017,10357,11351,15972,21084
12,충남,1279,2891,6515,9573,12151,14021,15907,16990,19386,...,4493,8369,11481,16888,18175,19904,22147,23353,24682,29677
13,전북,1815,2254,4251,6012,6563,8904,9300,12273,13247,...,1426,1587,2310,2756,3206,4587,4749,4983,5195,7244
14,전남,405,2980,4174,8910,12599,17228,20581,21344,23619,...,2246,2914,3254,3735,3991,4231,4448,4692,5208,5790
15,경북,273,1606,4015,6210,6964,7771,9480,16040,19274,...,6684,6969,8264,9238,9478,10483,11345,11692,14351,18890
16,경남,845,3056,3788,4827,8691,11784,13162,13516,18235,...,5553,5766,6903,7952,8583,10038,14262,15461,15631,21971
17,제주,152,333,744,1070,1267,2011,2715,3462,4268,...,959,1137,1357,1471,1858,2028,2254,2456,2557,3264
18,부문별,26183,59830,105184,149793,186743,230761,277354,312860,358990,...,74558,102482,125974,149860,171677,200155,218641,244777,273121,428244
19,공공부문,1421,5902,9099,9214,9971,11589,13186,13235,14504,...,636,2485,3019,2819,3962,4125,4979,5103,8161,129047
20,민간부문,24762,53928,96085,140579,176772,219172,264168,299625,344486,...,73922,99997,122955,147041,167715,196030,213662,239674,264960,299197

In [92]:
df_melted = data1.melt(id_vars='계정항목', var_name='날짜', value_name='실거래가격지수')
df_melted

            계정항목       날짜  실거래가격지수
0             전국  2021/01    123.6
1             서울  2021/01    167.6
2            도심권  2021/01    157.7
3            동북권  2021/01    177.0
4            동남권  2021/01    162.7
...          ...      ...      ...
1339          경남  2024/12     94.7
1340          제주  2024/12    107.0
1341      광역시 1)  2024/12    111.5
1342    지방광역시 2)  2024/12    108.8
1343      지방도 3)  2024/12    103.3

[1344 rows x 3 columns]

In [93]:
df_melted['날짜'] = pd.to_datetime(df_melted['날짜'] + '/01', format='%Y/%m/%d')
df_melted

            계정항목         날짜  실거래가격지수
0             전국 2021-01-01    123.6
1             서울 2021-01-01    167.6
2            도심권 2021-01-01    157.7
3            동북권 2021-01-01    177.0
4            동남권 2021-01-01    162.7
...          ...        ...      ...
1339          경남 2024-12-01     94.7
1340          제주 2024-12-01    107.0
1341      광역시 1) 2024-12-01    111.5
1342    지방광역시 2) 2024-12-01    108.8
1343      지방도 3) 2024-12-01    103.3

[1344 rows x 3 columns]

In [94]:
df_melted.rename(columns={'계정항목': '지역'}, inplace=True)

In [95]:
df_melted = df_melted.sort_values(by=['지역', '날짜']).reset_index(drop=True)

In [96]:
df_melted['지역'].unique()

array(['    도심권', '    동남권', '    동북권', '    서남권', '    서북권', '  강원',
       '  경기', '  경남', '  경북', '  광역시 1)', '  광주', '  대구', '  대전', '  부산',
       '  서울', '  세종', '  수도권', '  울산', '  인천', '  전남', '  전북', '  제주',
       '  지방', '  지방광역시 2)', '  지방도 3)', '  충남', '  충북', '전국'],
      dtype=object)

In [41]:
valid_regions = data['지역'].unique()
valid_regions

array(['서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종', '경기', '강원', '충북',
       '충남', '전북', '전남', '경북', '경남', '제주'], dtype=object)

In [56]:
df_melted.columns = df_melted.columns.str.strip()

In [98]:
df_melted = df_melted[df_melted['지역'].isin(valid_regions)].copy()
df_melted

      지역         날짜  실거래가격지수
240   강원 2021-01-01     95.7
241   강원 2021-02-01     96.8
242   강원 2021-03-01     98.2
243   강원 2021-04-01     99.4
244   강원 2021-05-01    100.1
...   ..        ...      ...
1291  충북 2024-08-01    109.4
1292  충북 2024-09-01    109.8
1293  충북 2024-10-01    109.5
1294  충북 2024-11-01    109.0
1295  충북 2024-12-01    108.0

[816 rows x 3 columns]

In [97]:
df_melted['지역'] = df_melted['지역'].str.strip()
df_melted['지역'].unique()

array(['도심권', '동남권', '동북권', '서남권', '서북권', '강원', '경기', '경남', '경북',
       '광역시 1)', '광주', '대구', '대전', '부산', '서울', '세종', '수도권', '울산', '인천',
       '전남', '전북', '제주', '지방', '지방광역시 2)', '지방도 3)', '충남', '충북', '전국'],
      dtype=object)

In [99]:
df_melted

      지역         날짜  실거래가격지수
240   강원 2021-01-01     95.7
241   강원 2021-02-01     96.8
242   강원 2021-03-01     98.2
243   강원 2021-04-01     99.4
244   강원 2021-05-01    100.1
...   ..        ...      ...
1291  충북 2024-08-01    109.4
1292  충북 2024-09-01    109.8
1293  충북 2024-10-01    109.5
1294  충북 2024-11-01    109.0
1295  충북 2024-12-01    108.0

[816 rows x 3 columns]

In [100]:
df_merged = pd.merge(
    df_merged,
    df_melted,
    on=['날짜', '지역'],
    how='left'  # 필요한 경우 'inner'로도 가능
)
df_merged

            날짜  지역    주택구입부담지수  기준금리    거래량      인구수    물가지수  주택인허가실적  실거래가격지수
0   2021-01-01  서울  163.970000  0.50  12275  9657969  100.86     2695    167.6
1   2021-02-01  서울  166.200000  0.50  12707  9648606  101.33     9599    169.9
2   2021-03-01  서울  168.430000  0.50  11122  9598484  101.57    16290    170.8
3   2021-04-01  서울  169.870000  0.50  11873  9588711  101.68    26397    171.9
4   2021-05-01  서울  172.900000  0.50  13145  9575355  101.74    30915    175.4
..         ...  ..         ...   ...    ...      ...     ...      ...      ...
811 2024-08-01  제주   72.300000  3.50    532   671540  114.25     2028    109.4
812 2024-09-01  제주   73.827162  3.50    485   671064  114.09     2254    109.7
813 2024-10-01  제주   76.002123  3.25    614   670837  114.34     2456    111.4
814 2024-11-01  제주   75.600000  3.00    557   670632  114.11     2557    109.7
815 2024-12-01  제주   75.197877  3.00    534   670368  114.37     3264    107.0

[816 rows x 9 columns]

In [101]:
df_merged

            날짜  지역    주택구입부담지수  기준금리    거래량      인구수    물가지수  주택인허가실적  실거래가격지수
0   2021-01-01  서울  163.970000  0.50  12275  9657969  100.86     2695    167.6
1   2021-02-01  서울  166.200000  0.50  12707  9648606  101.33     9599    169.9
2   2021-03-01  서울  168.430000  0.50  11122  9598484  101.57    16290    170.8
3   2021-04-01  서울  169.870000  0.50  11873  9588711  101.68    26397    171.9
4   2021-05-01  서울  172.900000  0.50  13145  9575355  101.74    30915    175.4
..         ...  ..         ...   ...    ...      ...     ...      ...      ...
811 2024-08-01  제주   72.300000  3.50    532   671540  114.25     2028    109.4
812 2024-09-01  제주   73.827162  3.50    485   671064  114.09     2254    109.7
813 2024-10-01  제주   76.002123  3.25    614   670837  114.34     2456    111.4
814 2024-11-01  제주   75.600000  3.00    557   670632  114.11     2557    109.7
815 2024-12-01  제주   75.197877  3.00    534   670368  114.37     3264    107.0

[816 rows x 9 columns]

In [102]:
df_merged.to_excel('통합_1.xlsx', index=False)