In [1]:
import pandas as pd

In [2]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Collecting et-xmlfile
  Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip available: 22.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
data1 = pd.read_excel('capstone/지역별 주택구입부담지수 (월별).xlsx')
data1

,Unnamed: 0,서울,부산,대구,인천,광주,대전,울산,세종,경기,강원,충북,충남,전북,전남,경북,경남,제주
0,2021년 1월,163.97,65.27,69.500000,60.070000,45.170000,65.430000,53.270000,134.130000,84.200000,31.570000,31.130000,33.730000,28.500000,28.670000,26.530000,37.430000,70.000000
1,2021년 2월,166.20,66.10,70.200000,63.100000,45.900000,66.400000,53.500000,135.700000,86.500000,31.700000,31.700000,34.200000,28.800000,28.800000,26.700000,37.600000,69.200000
2,2021년 3월,168.43,66.93,70.900000,66.130000,46.630000,67.370000,53.730000,137.270000,88.800000,31.830000,32.270000,34.670000,29.100000,28.930000,26.870000,37.770000,68.400000
3,2021년 4월,169.87,67.73,71.930000,69.430000,47.630000,67.270000,53.470000,139.770000,90.470000,31.670000,32.830000,35.000000,29.130000,28.900000,26.700000,37.730000,66.300000
4,2021년 5월,172.90,68.60,72.300000,72.200000,48.100000,69.300000,54.200000,140.400000,93.400000,32.100000,33.400000,35.600000,29.700000,29.200000,27.200000,38.100000,66.800000
5,2021년 6월,175.93,69.47,72.670000,74.970000,48.570000,71.330000,54.930000,141.030000,96.330000,32.530000,33.970000,36.200000,30.270000,29.500000,27.700000,38.470000,67.300000
6,2021년 7월,176.27,67.57,71.670000,76.870000,46.200000,72.630000,54.870000,141.470000,98.370000,31.830000,33.400000,36.070000,29.800000,29.130000,27.230000,37.600000,62.770000
7,2021년 8월,182.00,71.20,73.400000,80.500000,49.500000,75.400000,56.400000,142.300000,102.200000,33.400000,35.100000,37.400000,31.400000,30.100000,28.700000,39.200000,66.800000
8,2021년 9월,187.73,74.83,75.130000,84.130000,52.800000,78.170000,57.930000,143.130000,106.030000,34.970000,36.800000,38.730000,33.000000,31.070000,30.170000,40.800000,70.830000
9,2021년 10월,197.70,81.50,78.300000,90.400000,58.770000,83.500000,60.830000,146.800000,113.070000,37.530000,39.900000,40.930000,35.770000,32.800000,32.900000,43.530000,78.230000
10,2021년 11월,199.20,82.10,78.600000,91.400000,59.400000,83.700000,61.000000,144.800000,113.700000,38.100000,40.200000,41.400000,36.200000,33.000000,33.100000,44.000000,78.900000
11,2021년 12월,200.70,82.70,78.900000,92.400000,60.030000,83.900000,61.170000,142.800000,114.330000,38.670000,40.500000,41.870000,36.630000,33.200000,33.300000,44.470000,79.500000
12,2022년 1월,203.60,83.97,79.270000,94.500000,61.000000,84.370000,61.400000,140.630000,115.530000,39.330000,41.030000,42.500000,37.400000,33.700000,33.400000,45.270000,79.530000
13,2022년 2월,203.70,83.90,78.600000,94.400000,61.300000,84.300000,61.500000,138.800000,115.600000,39.800000,41.100000,42.800000,37.500000,33.600000,33.700000,45.400000,80.900000
14,2022년 3월,203.80,83.83,77.930000,94.300000,61.600000,84.230000,61.600000,136.970000,115.670000,40.270000,41.170000,43.100000,37.600000,33.500000,34.000000,45.530000,82.270000
15,2022년 4월,200.47,82.23,75.270000,92.500000,60.800000,83.270000,60.930000,132.870000,114.230000,40.100000,40.530000,42.830000,36.830000,32.400000,33.770000,44.970000,83.030000
16,2022년 5월,204.00,83.70,76.600000,94.100000,62.200000,84.100000,61.800000,133.300000,115.800000,41.200000,41.300000,43.700000,37.800000,33.300000,34.600000,45.800000,85.000000
17,2022년 6월,207.53,85.17,77.930000,95.700000,63.600000,84.930000,62.670000,133.730000,117.370000,42.300000,42.070000,44.570000,38.770000,34.200000,35.430000,46.630000,86.970000
18,2022년 7월,207.24,85.66,83.687345,103.363479,67.760321,90.149463,65.982860,144.706451,126.056065,45.397535,44.626597,47.349821,41.462362,36.687445,37.831051,49.196535,91.778482
19,2022년 8월,214.60,88.10,80.600000,98.900000,66.400000,86.600000,64.400000,134.600000,120.500000,44.500000,43.600000,46.300000,40.700000,36.000000,37.100000,48.300000,90.900000
20,2022년 9월,221.96,90.54,77.512655,94.436521,65.039679,83.050537,62.817140,124.493549,114.943935,43.602465,42.573403,45.250179,39.937638,35.312555,36.368949,47.403465,90.021518
21,2022년 10월,208.38,86.70,76.525332,93.260818,65.722698,81.783267,64.051298,112.792449,113.156612,44.164588,43.237390,45.959526,40.634589,35.582228,36.727661,48.201815,93.152253
22,2022년 11월,198.60,83.20,73.700000,88.500000,64.100000,78.500000,61.400000,109.500000,107.500000,43.000000,41.700000,44.400000,39.500000,34.900000,35.900000,46.900000,90.700000
23,2022년 12월,188.82,79.70,70.874668,83.739182,62.477302,75.216733,58.748702,106.207551,101.843388,41.835412,40.162610,42.840474,38.365411,34.217772,35.072339,45.598185,88.247747
24,2023년 1월,180.00,76.81,68.718213,79.134049,62.602859,72.552198,56.389368,104.085567,96.573692,41.197997,38.784570,41.874533,38.019665,34.775111,35.343342,45.226730,86.390059
25,2023년 2월,175.50,75.20,66.700000,77.100000,61.000000,71.000000,55.300000,102.700000,94.000000,40.700000,38.300000,41.000000,37.200000,33.800000,34.400000,44.300000,85.000000
26,2023년 3월,171.01,73.59,64.681787,75.065951,59.397141,69.447802,54.210632,101.314433,91.426308,40.202003,37.815430,40.125467,36.380335,32.824889,33.456658,43.373270,83.609941
27,2023년 4월,167.67,72.62,63.164264,73.631874,58.118348,68.324372,54.230998,97.133429,88.905647,40.356718,38.006742,39.855854,35.857855,31.963510,32.533824,42.706994,84.176727
28,2023년 5월,165.20,71.70,62.200000,72.400000,57.300000,67.600000,53.000000,100.300000,88.000000,39.900000,37.500000,39.100000,35.400000,31.500000,32.200000,42.300000,82.700000
29,2023년 6월,162.73,70.78,61.235736,71.168126,56.481652,66.875628,51.769002,103.466571,87.094353,39.443282,36.993258,38.344146,34.942145,31.036490,31.866176,41.893006,81.223273
30,2023년 7월,164.33,72.10,61.857892,71.727727,56.955090,68.134086,51.419224,109.752369,88.775171,40.108199,37.456622,38.533710,35.511529,31.416366,32.489573,42.930897,81.988980
31,2023년 8월,161.40,70.50,60.600000,70.300000,56.100000,66.900000,50.500000,107.800000,87.200000,39.400000,36.800000,37.700000,34.800000,30.800000,31.900000,42.000000,80.000000
32,2023년 9월,158.47,68.90,59.342108,68.872273,55.244910,65.665914,49.580776,105.847631,85.624829,38.691801,36.143378,36.866290,34.088471,30.183634,31.310427,41.069103,78.011020
33,2023년 10월,159.19,68.62,59.619884,68.451622,55.867722,65.794027,50.014652,106.451951,85.851900,38.837278,36.279448,36.683266,34.024489,30.154252,31.365717,40.992630,77.598858
34,2023년 11월,156.00,67.20,58.600000,67.500000,54.700000,64.600000,48.800000,104.200000,84.300000,38.100000,35.600000,36.000000,33.400000,29.600000,30.800000,40.100000,76.400000
35,2023년 12월,152.81,65.78,57.580116,66.548378,53.532278,63.405973,47.585348,101.948049,82.748100,37.362722,34.920552,35.316734,32.775511,29.045748,30.234283,39.207370,75.201142
36,2024년 1월,153.28,66.07,58.091844,67.617367,53.704808,63.853335,47.183883,102.677303,83.345412,37.538929,35.119306,35.522576,33.002149,29.238115,30.447922,39.355519,76.189462
37,2024년 2월,151.00,64.90,57.000000,66.600000,52.800000,62.900000,46.600000,100.500000,82.100000,37.000000,34.600000,35.000000,32.500000,28.800000,30.000000,38.600000,74.700000
38,2024년 3월,148.72,63.73,55.908156,65.582633,51.895192,61.946665,46.016117,98.322697,80.854588,36.461071,34.080694,34.477424,31.997851,28.361885,29.552078,37.844481,73.210538
39,2024년 4월,145.56,63.90,55.967063,64.539181,51.968645,62.328529,46.653758,98.355930,79.500928,35.737326,33.491336,34.645969,32.156626,27.810285,29.835563,37.569197,72.821794
40,2024년 5월,147.90,63.00,55.300000,65.200000,51.400000,61.600000,46.000000,96.500000,80.400000,36.300000,33.900000,34.300000,31.800000,28.200000,29.400000,37.300000,72.300000
41,2024년 6월,150.24,62.09,54.632937,65.860819,50.831355,60.871471,45.346242,94.644070,81.299072,36.862674,34.308664,33.954031,31.443374,28.589715,28.964437,37.030803,71.778206
42,2024년 7월,147.51,60.83,53.183595,63.846199,50.138171,59.610672,44.154786,91.837259,79.360887,36.110293,33.395746,33.395746,30.912065,27.742111,28.199930,36.642763,70.772838
43,2024년 8월,150.90,62.00,54.500000,65.400000,51.100000,61.100000,45.300000,93.600000,80.900000,37.000000,34.200000,34.200000,31.600000,28.600000,28.900000,37.300000,72.300000
44,2024년 9월,154.29,63.17,55.816405,66.953801,52.061829,62.589328,46.445214,95.362741,82.439113,37.889707,35.004254,35.004254,32.287935,29.457889,29.600070,37.957237,73.827162
45,2024년 10월,158.87,64.59,57.053057,69.234000,53.311188,64.799799,48.171546,97.653196,84.451371,39.202367,36.179048,36.179048,33.256506,30.837851,30.636297,38.299965,76.002123
46,2024년 11월,157.90,64.20,57.500000,68.700000,52.900000,64.300000,47.800000,96.900000,83.800000,38.900000,35.900000,35.900000,33.000000,30.600000,30.400000,38.600000,75.600000
47,2024년 12월,156.93,63.81,57.946943,68.166000,52.488812,63.800201,47.428454,96.146804,83.148629,38.597633,35.620952,35.620952,32.743494,30.362149,30.163703,38.900035,75.197877

In [5]:
data1 = data1.rename(columns={'Unnamed: 0': '날짜'})

In [14]:
data1['날짜'] = pd.to_datetime(data1['날짜'], format='%Y년 %m월')

# 패널 데이터(롱 포맷) 형태로 변환
panel_df1 = data1.melt(id_vars='날짜', var_name='지역', value_name='주택구입부담지수')

In [15]:
panel_df1

            날짜  지역    주택구입부담지수
0   2021-01-01  서울  163.970000
1   2021-02-01  서울  166.200000
2   2021-03-01  서울  168.430000
3   2021-04-01  서울  169.870000
4   2021-05-01  서울  172.900000
..         ...  ..         ...
811 2024-08-01  제주   72.300000
812 2024-09-01  제주   73.827162
813 2024-10-01  제주   76.002123
814 2024-11-01  제주   75.600000
815 2024-12-01  제주   75.197877

[816 rows x 3 columns]

In [20]:
data2 = pd.read_excel('capstone/한국은행 기준금리.xlsx')
data2

         날짜  기준금리
0   2021/01  0.50
1   2021/02  0.50
2   2021/03  0.50
3   2021/04  0.50
4   2021/05  0.50
5   2021/06  0.50
6   2021/07  0.50
7   2021/08  0.75
8   2021/09  0.75
9   2021/10  0.75
10  2021/11  1.00
11  2021/12  1.00
12  2022/01  1.25
13  2022/02  1.25
14  2022/03  1.25
15  2022/04  1.50
16  2022/05  1.75
17  2022/06  1.75
18  2022/07  2.25
19  2022/08  2.50
20  2022/09  2.50
21  2022/10  3.00
22  2022/11  3.25
23  2022/12  3.25
24  2023/01  3.50
25  2023/02  3.50
26  2023/03  3.50
27  2023/04  3.50
28  2023/05  3.50
29  2023/06  3.50
30  2023/07  3.50
31  2023/08  3.50
32  2023/09  3.50
33  2023/10  3.50
34  2023/11  3.50
35  2023/12  3.50
36  2024/01  3.50
37  2024/02  3.50
38  2024/03  3.50
39  2024/04  3.50
40  2024/05  3.50
41  2024/06  3.50
42  2024/07  3.50
43  2024/08  3.50
44  2024/09  3.50
45  2024/10  3.25
46  2024/11  3.00
47  2024/12  3.00
48  2025/01  3.00
49  2025/02  2.75
50  2025/03  2.75
51  2025/04  2.75
52  2025/05  2.50
53  2025/06  2.50
54  2025/07  2.50
55  2025/08  2.50
56  2025/09  2.50

In [22]:
data2['날짜'] = pd.to_datetime(data2['날짜'], format='%Y/%m')
data2

           날짜  기준금리
0  2021-01-01  0.50
1  2021-02-01  0.50
2  2021-03-01  0.50
3  2021-04-01  0.50
4  2021-05-01  0.50
5  2021-06-01  0.50
6  2021-07-01  0.50
7  2021-08-01  0.75
8  2021-09-01  0.75
9  2021-10-01  0.75
10 2021-11-01  1.00
11 2021-12-01  1.00
12 2022-01-01  1.25
13 2022-02-01  1.25
14 2022-03-01  1.25
15 2022-04-01  1.50
16 2022-05-01  1.75
17 2022-06-01  1.75
18 2022-07-01  2.25
19 2022-08-01  2.50
20 2022-09-01  2.50
21 2022-10-01  3.00
22 2022-11-01  3.25
23 2022-12-01  3.25
24 2023-01-01  3.50
25 2023-02-01  3.50
26 2023-03-01  3.50
27 2023-04-01  3.50
28 2023-05-01  3.50
29 2023-06-01  3.50
30 2023-07-01  3.50
31 2023-08-01  3.50
32 2023-09-01  3.50
33 2023-10-01  3.50
34 2023-11-01  3.50
35 2023-12-01  3.50
36 2024-01-01  3.50
37 2024-02-01  3.50
38 2024-03-01  3.50
39 2024-04-01  3.50
40 2024-05-01  3.50
41 2024-06-01  3.50
42 2024-07-01  3.50
43 2024-08-01  3.50
44 2024-09-01  3.50
45 2024-10-01  3.25
46 2024-11-01  3.00
47 2024-12-01  3.00
48 2025-01-01  3.00
49 2025-02-01  2.75
50 2025-03-01  2.75
51 2025-04-01  2.75
52 2025-05-01  2.50
53 2025-06-01  2.50
54 2025-07-01  2.50
55 2025-08-01  2.50
56 2025-09-01  2.50

In [24]:
merged_df = pd.merge(panel_df1, data2, on='날짜', how='left')
merged_df

            날짜  지역    주택구입부담지수  기준금리
0   2021-01-01  서울  163.970000  0.50
1   2021-02-01  서울  166.200000  0.50
2   2021-03-01  서울  168.430000  0.50
3   2021-04-01  서울  169.870000  0.50
4   2021-05-01  서울  172.900000  0.50
..         ...  ..         ...   ...
811 2024-08-01  제주   72.300000  3.50
812 2024-09-01  제주   73.827162  3.50
813 2024-10-01  제주   76.002123  3.25
814 2024-11-01  제주   75.600000  3.00
815 2024-12-01  제주   75.197877  3.00

[816 rows x 4 columns]

In [26]:
merged_df['지역'].unique()

array(['서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종', '경기', '강원', '충북',
       '충남', '전북', '전남', '경북', '경남', '제주'], dtype=object)

In [42]:
data3 = pd.read_excel('capstone/주택매매거래량(단위-건수)-2021~2025.03 월별.xlsx')
data3['구분'].unique()

array(['서울', '인천', '경기', '부산', '대구', '대전', '광주', '울산', '경남', '경북', '충남',
       '전남', '전북', '충북', '강원', '제주', '세종'], dtype=object)

In [44]:
data3 = data3.melt(id_vars='구분', var_name='날짜', value_name='거래량')
data3 = data3.rename(columns={'구분': '지역'})
data3

     지역      날짜    거래량
0    서울  '21.01  12275
1    인천  '21.01   7344
2    경기  '21.01  27513
3    부산  '21.01   4997
4    대구  '21.01   2954
..   ..     ...    ...
845  전북  '25.02   2163
846  충북  '25.02   2102
847  강원  '25.02   1926
848  제주  '25.02    545
849  세종  '25.02    427

[850 rows x 3 columns]

In [45]:
data3['날짜'] = pd.to_datetime(data3['날짜'].str.replace("'", "20"), format='%Y.%m')

In [47]:
merged_df = pd.merge(merged_df, data3, on=['날짜', '지역'], how='left')
merged_df

            날짜  지역    주택구입부담지수  기준금리  거래량_x  거래량_y
0   2021-01-01  서울  163.970000  0.50  12275  12275
1   2021-02-01  서울  166.200000  0.50  12707  12707
2   2021-03-01  서울  168.430000  0.50  11122  11122
3   2021-04-01  서울  169.870000  0.50  11873  11873
4   2021-05-01  서울  172.900000  0.50  13145  13145
..         ...  ..         ...   ...    ...    ...
811 2024-08-01  제주   72.300000  3.50    532    532
812 2024-09-01  제주   73.827162  3.50    485    485
813 2024-10-01  제주   76.002123  3.25    614    614
814 2024-11-01  제주   75.600000  3.00    557    557
815 2024-12-01  제주   75.197877  3.00    534    534

[816 rows x 6 columns]

In [57]:
data4 = pd.read_excel('capstone/주민등록인구(지도, 년, 월)_.xlsx')
data4

,행정구역별,2016.01,2016.02,2016.03,2016.04,2016.05,2016.06,2016.07,2016.08,2016.09,...,2024.12,2025.01,2025.02,2025.03,2025.04,2025.05,2025.06,2025.07,2025.08,2025.09
0,서울특별시,10018537,10014261,10009588,10002979,9995784,9989795,9981673,9971111,9964291,...,9331828,9330658,9334828,9335734,9331860,9328042,9325616,9323492,9321863,9318500
1,부산광역시,3513361,3513192,3512444,3511974,3510833,3509462,3508095,3507205,3505821,...,3266598,3263891,3262337,3259219,3256408,3254457,3252830,3251625,3249975,3248359
2,대구광역시,2487823,2486589,2486059,2485663,2485134,2484864,2484856,2485537,2485692,...,2363629,2363281,2362578,2360493,2359159,2357997,2357052,2357040,2356667,2356372
3,인천광역시,2927195,2928596,2929817,2932141,2933959,2935314,2937217,2938902,2940436,...,3021010,3023649,3027854,3031361,3033844,3037049,3039450,3041215,3043162,3046754
4,광주광역시,1472802,1472153,1471618,1471819,1472317,1472285,1472481,1472432,1472379,...,1408422,1407097,1405226,1402478,1400827,1399880,1399082,1398538,1397772,1397122
5,대전광역시,1518024,1517716,1517118,1516904,1516494,1516208,1516291,1516165,1516241,...,1439157,1438974,1439809,1439482,1439393,1439607,1439764,1440682,1441596,1442228
6,울산광역시,1173568,1173143,1172959,1172925,1173147,1173143,1173066,1173005,1172965,...,1098049,1097821,1095778,1095014,1094460,1094027,1093665,1093317,1092989,1092634
7,세종특별자치시,215418,220108,223461,225488,227972,230327,232117,234510,236134,...,390685,390910,391669,391812,391992,392211,392223,392154,391984,392230
8,경기도,12536474,12551398,12565891,12578597,12594829,12610877,12629325,12649894,12666278,...,13694685,13699647,13698657,13699381,13702756,13706488,13711404,13715016,13720015,13721178
9,강원특별자치도,1549193,1548016,1547845,1548170,1547821,1548603,1548636,1548844,1549483,...,1517766,1515822,1513735,1512969,1512088,1511341,1510615,1510181,1509670,1509396
10,충청북도,1583982,1583781,1584325,1585312,1586414,1586943,1587539,1588025,1588548,...,1591177,1590666,1590107,1590512,1590735,1590956,1591045,1591815,1591965,1592431
11,충청남도,2078572,2080030,2081092,2082319,2084034,2085844,2086737,2088268,2089831,...,2136574,2135815,2135340,2135628,2135908,2135908,2135890,2136299,2136195,2136551
12,전북특별자치도,1868354,1867534,1866691,1866184,1865634,1865900,1865612,1865232,1864729,...,1738690,1737351,1735008,1733574,1732439,1731309,1730258,1729337,1728330,1727716
13,전라남도,1906904,1905700,1905239,1904917,1904449,1904314,1903692,1902883,1902077,...,1788819,1787592,1785487,1785193,1785003,1784116,1783484,1782183,1780646,1779599
14,경상북도,2701160,2701055,2701148,2701238,2701912,2702385,2702210,2701293,2701445,...,2531384,2528641,2524067,2523173,2522609,2520934,2519474,2516753,2514198,2512441
15,경상남도,3364764,3364695,3365021,3366658,3367730,3368792,3369271,3369074,3369695,...,3228380,3226599,3221132,3219574,3218731,3217584,3216105,3214016,3212001,3210425
16,제주특별자치도,625451,627442,629220,631061,632802,634274,635800,637172,638199,...,670368,669460,668205,667739,667513,667242,666625,666226,665953,665610

In [58]:
data4 = data4.melt(id_vars='행정구역별', var_name='날짜', value_name='인구수')
data4['날짜'] = pd.to_datetime(data4['날짜'], format='%Y.%m')
data4 = data4.rename(columns={'행정구역별': '지역'})

In [59]:
data4

           지역         날짜       인구수
0       서울특별시 2016-01-01  10018537
1       부산광역시 2016-01-01   3513361
2       대구광역시 2016-01-01   2487823
3       인천광역시 2016-01-01   2927195
4       광주광역시 2016-01-01   1472802
...       ...        ...       ...
1984  전북특별자치도 2025-09-01   1727716
1985     전라남도 2025-09-01   1779599
1986     경상북도 2025-09-01   2512441
1987     경상남도 2025-09-01   3210425
1988  제주특별자치도 2025-09-01    665610

[1989 rows x 3 columns]

In [60]:
mapping = {
    '서울특별시': '서울',
    '부산광역시': '부산',
    '대구광역시': '대구',
    '인천광역시': '인천',
    '광주광역시': '광주',
    '대전광역시': '대전',
    '울산광역시': '울산',
    '세종특별자치시': '세종',
    '경기도': '경기',
    '강원특별자치도': '강원',
    '충청북도': '충북',
    '충청남도': '충남',
    '전북특별자치도': '전북',
    '전라남도': '전남',
    '경상북도': '경북',
    '경상남도': '경남',
    '제주특별자치도': '제주',
}
data4['지역'] = data4['지역'].replace(mapping)
data4

      지역         날짜       인구수
0     서울 2016-01-01  10018537
1     부산 2016-01-01   3513361
2     대구 2016-01-01   2487823
3     인천 2016-01-01   2927195
4     광주 2016-01-01   1472802
...   ..        ...       ...
1984  전북 2025-09-01   1727716
1985  전남 2025-09-01   1779599
1986  경북 2025-09-01   2512441
1987  경남 2025-09-01   3210425
1988  제주 2025-09-01    665610

[1989 rows x 3 columns]

In [62]:
final_df = pd.merge(merged_df, data4, on=['날짜', '지역'], how='left')
final_df = final_df.drop(columns=['거래량_y'])
final_df = final_df.rename(columns={'거래량_x': '거래량'})
final_df

            날짜  지역    주택구입부담지수  기준금리    거래량      인구수
0   2021-01-01  서울  163.970000  0.50  12275  9657969
1   2021-02-01  서울  166.200000  0.50  12707  9648606
2   2021-03-01  서울  168.430000  0.50  11122  9598484
3   2021-04-01  서울  169.870000  0.50  11873  9588711
4   2021-05-01  서울  172.900000  0.50  13145  9575355
..         ...  ..         ...   ...    ...      ...
811 2024-08-01  제주   72.300000  3.50    532   671540
812 2024-09-01  제주   73.827162  3.50    485   671064
813 2024-10-01  제주   76.002123  3.25    614   670837
814 2024-11-01  제주   75.600000  3.00    557   670632
815 2024-12-01  제주   75.197877  3.00    534   670368

[816 rows x 6 columns]

In [63]:
final_df.to_excel('통합.xlsx', index=False)

In [1]:
import pandas as pd

In [2]:
final_df = pd.read_excel('통합.xlsx')
final_df

            날짜  지역    주택구입부담지수  기준금리    거래량      인구수
0   2021-01-01  서울  163.970000  0.50  12275  9657969
1   2021-02-01  서울  166.200000  0.50  12707  9648606
2   2021-03-01  서울  168.430000  0.50  11122  9598484
3   2021-04-01  서울  169.870000  0.50  11873  9588711
4   2021-05-01  서울  172.900000  0.50  13145  9575355
..         ...  ..         ...   ...    ...      ...
811 2024-08-01  제주   72.300000  3.50    532   671540
812 2024-09-01  제주   73.827162  3.50    485   671064
813 2024-10-01  제주   76.002123  3.25    614   670837
814 2024-11-01  제주   75.600000  3.00    557   670632
815 2024-12-01  제주   75.197877  3.00    534   670368

[816 rows x 6 columns]

In [27]:
df = pd.read_excel('capstone/소비자물가지수.xlsx')

In [28]:
df['년도'] = df['년도'].astype(str).str.replace('o', '0', regex=False)

In [ ]:
df['날짜'] = pd.to_datetime(df['년도'], format='%Y.%m', errors='coerce')

,년도,서울,부산,대구,인천,광주,대전,울산,세종,경기,강원,충북,충남,전북,전남,경북,경남,제주,날짜
0,2025.09,116.15,117.12,116.96,117.54,117.20,116.69,117.03,117.23,117.08,118.56,117.75,117.50,117.29,118.08,117.77,117.48,116.58,2025-09-01
1,2025.08,115.75,116.61,116.32,116.85,116.56,115.98,116.38,116.57,116.56,117.73,116.83,116.69,116.26,117.16,116.95,116.73,115.78,2025-08-01
2,2025.07,115.79,116.60,116.43,117.14,116.59,116.03,116.33,116.64,116.64,117.89,117.10,116.79,116.43,117.33,117.08,116.54,115.88,2025-07-01
3,2025.06,115.52,116.26,116.29,116.93,116.55,115.89,115.89,116.30,116.35,117.92,117.06,116.68,116.37,117.22,116.91,116.34,115.64,2025-06-01
4,2025.05,115.51,116.28,116.26,116.90,116.46,115.90,115.89,116.47,116.27,117.85,116.96,116.71,116.39,117.16,117.02,116.24,115.67,2025-05-01
5,2025.04,115.64,116.39,116.45,116.98,116.76,115.92,116.00,116.48,116.35,117.96,117.04,116.74,116.55,117.51,117.11,116.41,115.67,2025-04-01
6,2025.03,115.40,116.39,116.34,116.91,116.57,115.76,115.94,116.55,116.31,118.02,116.88,116.72,116.54,117.41,117.06,116.34,115.59,2025-03-01
7,2025.02,115.21,116.10,116.10,116.96,116.45,115.58,115.82,116.38,116.06,117.74,116.71,116.56,116.32,117.10,116.77,116.24,115.54,2025-02-01
8,2025.01,114.90,115.75,115.57,116.46,115.94,115.33,115.43,115.81,115.71,117.31,116.37,116.15,115.94,116.62,116.36,115.78,115.17,2025-01-01
9,2024.12,114.24,114.97,114.84,115.52,115.14,114.57,114.56,114.92,114.90,116.36,115.50,115.35,115.07,115.58,115.46,115.00,114.37,2024-12-01
10,2024.11,113.73,114.29,114.49,114.84,114.61,114.23,114.18,114.31,114.44,115.75,114.88,114.74,114.54,115.03,115.06,114.53,114.11,2024-11-01
11,2024.10,114.04,114.76,114.73,115.18,114.93,114.38,114.49,114.58,114.68,116.14,115.22,114.98,114.80,115.64,115.33,114.74,114.34,2024-10-01
12,2024.09,113.92,114.67,114.73,115.19,114.81,114.35,114.41,114.65,114.65,116.19,115.41,115.00,114.71,115.63,115.28,114.74,114.09,2024-09-01
13,2024.08,113.94,114.39,114.54,115.17,114.95,114.09,114.25,114.52,114.51,116.02,115.21,114.95,114.43,115.34,115.18,114.51,114.25,2024-08-01
14,2024.07,113.46,113.97,114.12,114.71,114.61,113.82,113.91,114.15,114.16,115.48,114.64,114.41,114.11,114.92,114.76,114.04,113.99,2024-07-01
15,2024.06,113.17,113.71,113.86,114.48,114.38,113.54,113.51,113.94,113.76,115.19,114.62,114.12,113.87,114.68,114.56,113.86,113.73,2024-06-01
16,2024.05,113.42,113.87,114.00,114.78,114.79,113.70,113.81,114.15,114.01,115.67,114.86,114.52,114.16,115.08,114.99,114.07,114.03,2024-05-01
17,2024.04,113.37,113.92,113.87,114.56,114.62,113.84,113.95,114.02,113.89,115.63,114.71,114.36,114.10,115.01,114.83,113.94,114.08,2024-04-01
18,2024.03,113.02,113.98,114.08,114.79,114.37,113.67,113.87,113.63,113.90,115.53,114.67,114.39,114.06,114.92,114.83,114.19,113.84,2024-03-01
19,2024.02,113.07,113.84,113.95,114.44,114.11,113.40,113.75,113.50,113.64,115.17,114.49,114.30,113.82,114.60,114.49,114.10,113.77,2024-02-01
20,2024.01,112.60,113.11,113.14,113.76,113.47,112.91,112.98,112.79,113.05,114.51,113.76,113.71,113.20,113.98,113.80,113.32,113.08,2024-01-01
21,2023.12,112.25,112.67,112.56,113.27,112.92,112.34,112.57,112.32,112.57,114.12,113.34,113.26,112.81,113.38,113.50,112.94,112.70,2023-12-01
22,2023.11,111.98,112.57,112.74,113.12,112.95,112.15,112.44,112.27,112.58,114.25,113.47,113.33,112.72,113.50,113.50,112.98,112.80,2023-11-01
23,2023.10,112.51,113.12,113.38,113.79,113.47,112.86,113.39,112.89,113.11,114.71,114.11,114.20,113.33,114.19,114.21,113.66,113.59,2023-10-01
24,2023.09,112.08,112.44,112.95,113.17,112.98,112.43,112.87,112.67,112.78,114.21,113.83,113.79,112.85,113.73,113.89,113.22,113.25,2023-09-01
25,2023.08,111.69,111.89,112.57,112.69,112.48,111.92,112.19,111.94,112.22,113.44,113.09,112.93,112.23,112.91,113.10,112.41,112.45,2023-08-01
26,2023.07,110.63,111.10,111.47,111.61,111.51,111.12,111.07,111.45,111.27,112.40,112.12,111.90,111.08,111.70,111.93,111.45,111.48,2023-07-01
27,2023.06,110.50,110.90,111.31,111.26,111.40,110.84,110.97,111.29,111.13,112.55,112.12,111.84,111.04,111.69,111.88,111.34,111.47,2023-06-01
28,2023.05,110.37,110.84,111.27,111.31,111.24,110.80,110.94,111.13,111.13,112.58,112.07,111.87,111.08,111.78,111.99,111.20,111.46,2023-05-01
29,2023.04,109.94,110.41,111.13,110.95,110.95,110.39,110.45,110.84,110.80,112.27,111.70,111.58,110.79,111.40,111.63,110.75,111.33,2023-04-01
30,2023.03,109.77,110.24,110.93,110.75,110.82,110.14,110.27,110.48,110.52,111.97,111.30,111.42,110.67,110.96,111.22,110.52,111.08,2023-03-01
31,2023.02,109.60,110.00,110.68,110.61,110.34,110.06,109.99,110.20,110.38,111.69,110.89,111.08,110.56,110.66,111.01,110.50,111.03,2023-02-01
32,2023.01,109.22,109.83,110.43,110.48,110.07,109.85,109.95,110.06,110.05,111.66,110.63,110.96,110.33,110.58,110.82,110.13,110.76,2023-01-01
33,2022.12,108.46,108.83,109.59,109.66,109.10,109.03,109.07,109.48,109.26,110.73,109.94,110.09,109.43,109.71,110.16,109.38,109.87,2022-12-01
34,2022.11,108.00,108.72,109.48,109.36,109.10,108.79,108.90,109.47,109.12,110.48,109.88,109.91,109.45,109.69,110.24,109.23,109.96,2022-11-01
35,2022.10,108.12,108.79,109.61,109.40,109.16,108.94,109.13,109.70,109.13,110.54,110.16,110.11,109.56,109.93,110.28,109.31,110.28,2022-10-01
36,2022.09,107.78,108.38,109.29,108.94,108.80,108.53,108.72,109.25,108.78,110.21,109.99,110.03,109.33,109.72,109.91,108.96,110.20,2022-09-01
37,2022.08,107.65,108.22,108.88,108.70,108.77,108.42,108.42,109.54,108.58,109.91,109.61,109.89,109.02,109.51,109.70,108.78,109.87,2022-08-01
38,2022.07,107.47,108.19,108.93,108.87,109.01,108.48,108.52,109.39,108.73,110.20,109.84,110.11,109.27,109.71,110.10,109.04,109.82,2022-07-01
39,2022.06,106.85,107.78,108.28,108.44,108.54,108.09,107.99,109.07,108.20,109.70,109.28,109.44,108.76,109.31,109.56,108.58,109.47,2022-06-01
40,2022.05,106.29,107.05,107.75,107.71,107.86,107.30,107.38,108.32,107.55,108.96,108.41,108.39,107.96,108.44,108.62,107.85,108.51,2022-05-01
41,2022.04,105.73,106.44,107.09,107.03,106.90,106.64,106.72,107.42,106.86,108.18,107.60,107.84,107.21,107.62,107.92,107.21,107.74,2022-04-01
42,2022.03,105.09,105.85,106.44,106.25,106.11,106.04,105.92,106.64,106.14,107.11,106.76,107.14,106.37,106.67,106.99,106.49,106.87,2022-03-01
43,2022.02,104.70,105.23,105.79,105.87,105.24,105.29,105.23,105.46,105.41,106.18,105.76,106.30,105.45,105.74,105.98,105.76,106.21,2022-02-01
44,2022.01,104.09,104.72,105.10,105.24,104.83,104.65,104.86,105.01,104.88,105.60,105.02,105.61,104.88,105.14,105.42,105.21,105.70,2022-01-01
45,2021.12,103.32,103.87,104.30,104.38,104.10,103.97,104.12,104.16,104.16,104.69,104.31,104.45,104.08,104.34,104.65,104.15,104.43,2021-12-01
46,2021.11,103.20,103.63,104.11,104.06,103.95,103.71,103.86,104.01,103.97,104.53,104.16,104.39,104.06,104.29,104.38,103.90,104.41,2021-11-01
47,2021.10,102.90,103.22,103.56,103.56,103.27,103.23,103.22,103.55,103.43,103.85,103.50,103.81,103.46,103.64,103.75,103.27,103.70,2021-10-01
48,2021.09,102.67,103.17,103.43,103.41,103.15,103.08,103.26,103.20,103.21,103.64,103.28,103.47,103.42,103.30,103.52,103.14,103.51,2021-09-01
49,2021.08,102.33,102.61,102.90,102.94,102.82,102.70,102.71,103.11,102.85,103.08,102.88,102.96,102.90,102.76,103.01,102.74,102.99,2021-08-01
50,2021.07,101.88,102.19,102.36,102.36,102.36,102.40,102.20,102.61,102.33,102.46,102.50,102.55,102.39,102.35,102.49,102.26,102.39,2021-07-01
51,2021.06,101.68,101.95,102.12,102.11,102.19,102.19,101.93,102.48,102.17,102.28,102.33,102.38,102.11,102.16,102.25,102.08,102.02,2021-06-01
52,2021.05,101.74,102.03,102.14,102.08,102.24,102.13,102.00,102.40,102.10,102.19,102.27,102.30,102.10,102.17,102.14,102.14,102.18,2021-05-01
53,2021.04,101.68,102.00,102.09,102.02,102.13,102.09,101.88,102.33,102.01,102.19,102.17,102.16,102.05,102.00,102.01,102.07,102.10,2021-04-01
54,2021.03,101.57,101.91,101.99,101.83,101.92,101.90,101.86,102.05,101.87,102.04,102.05,102.04,101.91,101.91,101.92,101.85,101.62,2021-03-01
55,2021.02,101.33,101.79,101.57,101.65,101.53,101.53,101.67,101.60,101.66,101.63,101.67,101.62,101.59,101.47,101.69,101.63,101.38,2021-02-01
56,2021.01,100.86,101.17,101.12,101.03,101.13,101.05,101.18,101.06,101.05,101.01,101.21,101.05,101.01,101.02,101.05,101.18,100.79,2021-01-01

In [30]:
df_long = df.melt(id_vars='날짜', var_name='지역', value_name='물가지수')

In [32]:
# 1. '날짜' 컬럼은 id_vars로 유지, '년도' 컬럼은 제외하고 melt 수행
value_vars = [col for col in df.columns if col not in ['날짜', '년도']]
df_long = df.melt(id_vars='날짜', value_vars=value_vars, var_name='지역', value_name='물가지수')

# 2. '지역'에 '년도'가 들어간 잘못된 행 제거
df_long = df_long[df_long['지역'] != '년도']

# 3. '물가지수'를 숫자형으로 변환 (문자열로 인식된 경우 대비)
df_long['물가지수'] = pd.to_numeric(df_long['물가지수'], errors='coerce')

# 4. 인덱스 재정렬
df_long = df_long.reset_index(drop=True)

In [33]:
df_long

            날짜  지역    물가지수
0   2025-09-01  서울  116.15
1   2025-08-01  서울  115.75
2   2025-07-01  서울  115.79
3   2025-06-01  서울  115.52
4   2025-05-01  서울  115.51
..         ...  ..     ...
964 2021-05-01  제주  102.18
965 2021-04-01  제주  102.10
966 2021-03-01  제주  101.62
967 2021-02-01  제주  101.38
968 2021-01-01  제주  100.79

[969 rows x 3 columns]

In [35]:
final_data = pd.merge(final_df, df_long, on=['날짜', '지역'], how='left') 
final_data

            날짜  지역    주택구입부담지수  기준금리    거래량      인구수    물가지수
0   2021-01-01  서울  163.970000  0.50  12275  9657969  100.86
1   2021-02-01  서울  166.200000  0.50  12707  9648606  101.33
2   2021-03-01  서울  168.430000  0.50  11122  9598484  101.57
3   2021-04-01  서울  169.870000  0.50  11873  9588711  101.68
4   2021-05-01  서울  172.900000  0.50  13145  9575355  101.74
..         ...  ..         ...   ...    ...      ...     ...
811 2024-08-01  제주   72.300000  3.50    532   671540  114.25
812 2024-09-01  제주   73.827162  3.50    485   671064  114.09
813 2024-10-01  제주   76.002123  3.25    614   670837  114.34
814 2024-11-01  제주   75.600000  3.00    557   670632  114.11
815 2024-12-01  제주   75.197877  3.00    534   670368  114.37

[816 rows x 7 columns]

In [36]:
final_data.to_excel('통합.xlsx', index=False)

48.0