In [58]:
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.svm import SVR

In [59]:
mesh_size =0.1
margin = 0

df = px.data.iris()
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [60]:
x = df[['sepal_width','sepal_length']]
y = df['petal_width']

model = SVR(C=1)
model.fit(x,y)

SVR(C=1)

In [61]:
x_min, x_max = x.sepal_width.min() - margin, x.sepal_width.max() + margin
y_min, y_max = x.sepal_length.min() - margin, x.sepal_length.max() + margin

xrange = np.arange(x_min, x_max, mesh_size)
yrange = np.arange(y_min, y_max, mesh_size)

xx, yy = np.meshgrid(xrange,yrange)

In [62]:
pred = model.predict(np.c_[xx.ravel(), yy.ravel()])
pred = pred.reshape(xx.shape)

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning:

X does not have valid feature names, but SVR was fitted with feature names

In [63]:
fig = px.scatter_3d(df, x='sepal_width', y='sepal_length', z = 'petal_width')
fig.update_traces(marker=dict(size = 3))
fig.add_traces(go.Surface(x=xrange, y=yrange, z=pred, name='pred_surface'))
fig.show()

In [64]:
from sklearn.linear_model import LinearRegression
import pandas as pd

In [65]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [70]:
x= df.drop(columns=['petal_width','species_id'])
x = pd.get_dummies(x, columns = ['species'], prefix_sep='=')
y = df['petal_width']

model = LinearRegression()
model.fit(x,y)

colors = ['Positive' if c >0 else 'Negative' for c in model.coef_]

In [72]:
fig = px.bar(
    x=x.columns, y=model.coef_, color = colors,
    color_discrete_sequence=['red', 'blue'],
    labels= dict(x= 'Feature', y='Linear coefficient')
)
fig.show()

In [75]:
df= px.data.iris()
x = df[['sepal_width', 'sepal_length']]
y = df['petal_width']

model = LinearRegression()
model.fit(x,y)
y_pred = model.predict(x)

In [78]:
fig = px.scatter(x=y, y=y_pred)
fig.add_shape(
    type = 'line', line=dict(dash='dash'),
    x0=y.min(), y0=y.min(),
    x1=y.max(), y1=y.max()
)
fig.show()