In [1]:
import pandas as pd

df = pd.DataFrame(
    {
        "미국": [2.1, 2.2, 2.3],
        "한국": [0.4, 0.5, 0.45],
        "중국": [10, 13, 15]
    },
    index=[2000,2010,2020]
)

df

       미국    한국  중국
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [2]:
df.columns = ['일본', '필리핀', '러시아']
df.values

array([[ 2.1 ,  0.4 , 10.  ],
       [ 2.2 ,  0.5 , 13.  ],
       [ 2.3 ,  0.45, 15.  ]])

In [3]:
df = pd.DataFrame(
    {
        "미국": [2.1, 2.2, 2.3],
        "한국": [0.4, 0.5, 0.45],
        "중국": [10, 13, 15],
        "년도": [2000, 2010, 2020]
    },
    index=[2000,2010,2020]
)
df = df.set_index('년도')
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [4]:
df = df.reset_index('년도')
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [5]:
df = df.set_index('년도')
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [6]:
df.loc[2000]
df.iloc[0]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [7]:
print(df['미국'][2000])

2.1

In [8]:
df['일본'] = [1,2,3]
df

       미국    한국  중국  일본
년도
2000  2.1  0.40  10   1
2010  2.2  0.50  13   2
2020  2.3  0.45  15   3

In [9]:
del df['일본']
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [10]:
df2 = df[['한국','중국']].copy()
df2

        한국  중국
년도
2000  0.40  10
2010  0.50  13
2020  0.45  15