In [46]:
import pandas as pd

In [47]:
df1 = pd.DataFrame({
    'id' : [1,2,3],
    'customer_id' : [1,2,3],
    'customer_name' : ['Robert','Peter','Dave']
})
df1

   id  customer_id customer_name
0   1            1        Robert
1   2            2         Peter
2   3            3          Dave

In [48]:
df2 = pd.DataFrame({
    'id' : [1,2,4],
    'order_id' : [100,200,300],
    'order_data' : ['2021-01-21','2021-02-03','2020-10-01']
})
df2

   id  order_id  order_data
0   1       100  2021-01-21
1   2       200  2021-02-03
2   4       300  2020-10-01

In [49]:
pd.concat([df1,df2])

   id  customer_id customer_name  order_id  order_data
0   1          1.0        Robert       NaN         NaN
1   2          2.0         Peter       NaN         NaN
2   3          3.0          Dave       NaN         NaN
0   1          NaN           NaN     100.0  2021-01-21
1   2          NaN           NaN     200.0  2021-02-03
2   4          NaN           NaN     300.0  2020-10-01

In [50]:
doc = pd.concat([df1,df2], axis = 1)

In [51]:
pd.merge(df1,df2, on = 'id')

   id  customer_id customer_name  order_id  order_data
0   1            1        Robert       100  2021-01-21
1   2            2         Peter       200  2021-02-03

In [52]:
df1 = df1.set_index('id')
df2 = df2.set_index('id')
pd.merge(df1,df2, left_index = True, right_index = True)

    customer_id customer_name  order_id  order_data
id
1             1        Robert       100  2021-01-21
2             2         Peter       200  2021-02-03

In [53]:
pd.merge(df1,df2, left_index = True, right_index = True ,how = 'outer')

    customer_id customer_name  order_id  order_data
id
1           1.0        Robert     100.0  2021-01-21
2           2.0         Peter     200.0  2021-02-03
3           3.0          Dave       NaN         NaN
4           NaN           NaN     300.0  2020-10-01