In [2]:
import pandas as pd

In [3]:
data = pd.read_excel('project.xlsx')
data

,v1성별,v2학년,v3소속대학,v41이용종류,v42이용종류,v43이용종류,v5이용목적,v6이용빈도,v7이용시간대,v8안전장비착용여부,...,v25보호장비 미착용 사고 위험 노출,v26보도 주행 보행자 충돌 위험성,v27음주 이용 사고 유발 가능성,v28보험 가입 의무화 필요성,v29인도 주행 허용 여부,v30특정 구간 속도 제한 여부,"v31번호판, 반사테이프 부착 의무화 여부",v32면허증 강화 필요성,v33반납 장소 지정 여부,v34안전 수칙 위반 처벌 및 단속 강화 필요 여부
0,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,4,5,2,3,4,4,4,5,5
1,2,1,3,1.0,0.0,0,1.0,5.0,2.0,1.0,...,5,5,5,4,4,4,4,4,5,4
2,1,4,5,0.0,1.0,0,2.0,1.0,3.0,1.0,...,4,4,5,2,1,5,4,4,5,5
3,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,5,1,5,5,5,5,5
4,1,2,5,0.0,1.0,0,2.0,4.0,3.0,1.0,...,1,5,5,1,1,5,5,2,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2,3,2,0.0,1.0,0,2.0,1.0,3.0,1.0,...,5,4,4,4,2,4,5,4,4,3
196,1,4,2,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,5,1,5,5,5,5,5
197,1,4,2,1.0,0.0,0,2.0,2.0,2.0,2.0,...,5,5,5,5,4,4,5,4,5,5
198,2,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,5,1,5,5,5,5,5
199,2,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,5,5,1,5,5,5,5,5

In [10]:
data.describe()

,v1성별,v2학년,v3소속대학,v41이용종류,v42이용종류,v43이용종류,v5이용목적,v6이용빈도,v7이용시간대,v8안전장비착용여부,...,v25보호장비 미착용 사고 위험 노출,v26보도 주행 보행자 충돌 위험성,v27음주 이용 사고 유발 가능성,v28보험 가입 의무화 필요성,v29인도 주행 허용 여부,v30특정 구간 속도 제한 여부,"v31번호판, 반사테이프 부착 의무화 여부",v32면허증 강화 필요성,v33반납 장소 지정 여부,v34안전 수칙 위반 처벌 및 단속 강화 필요 여부
count,200.00000,200.000000,200.000000,198.000000,198.000000,200.000000,105.000000,105.000000,105.000000,105.000000,...,200.000000,200.000000,200.000000,200.000,200.000000,200.000000,200.000000,200.000000,200.00000,200.000000
mean,1.32500,2.650000,3.900000,0.237374,0.373737,0.475000,1.933333,2.438095,2.180952,1.514286,...,4.325000,4.370000,4.660000,3.435,2.495000,4.220000,4.430000,4.290000,4.49000,4.370000
std,0.46955,1.124197,1.526977,0.426552,0.485022,0.500628,1.076557,1.480149,0.743962,0.761000,...,0.896321,0.903983,0.653095,1.402,1.399919,0.857483,0.733341,0.894371,0.82663,0.915034
min,1.00000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,2.000000,1.000,1.000000,2.000000,2.000000,2.000000,1.00000,1.000000
25%,1.00000,2.000000,3.000000,0.000000,0.000000,0.000000,1.000000,1.000000,2.000000,1.000000,...,4.000000,4.000000,4.750000,2.000,1.000000,4.000000,4.000000,4.000000,4.00000,4.000000
50%,1.00000,3.000000,5.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,1.000000,...,5.000000,5.000000,5.000000,4.000,2.000000,4.000000,5.000000,5.000000,5.00000,5.000000
75%,2.00000,4.000000,5.000000,0.000000,1.000000,1.000000,2.000000,4.000000,3.000000,2.000000,...,5.000000,5.000000,5.000000,5.000,4.000000,5.000000,5.000000,5.000000,5.00000,5.000000
max,2.00000,4.000000,5.000000,1.000000,1.000000,1.000000,4.000000,5.000000,3.000000,3.000000,...,5.000000,5.000000,5.000000,5.000,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000

In [9]:
39/105

0.37142857142857144

In [11]:
data['v4이용종류'] = 0
data['v4_1이용여부'] = 0
data

,v1성별,v2학년,v3소속대학,v41이용종류,v42이용종류,v43이용종류,v5이용목적,v6이용빈도,v7이용시간대,v8안전장비착용여부,...,v27음주 이용 사고 유발 가능성,v28보험 가입 의무화 필요성,v29인도 주행 허용 여부,v30특정 구간 속도 제한 여부,"v31번호판, 반사테이프 부착 의무화 여부",v32면허증 강화 필요성,v33반납 장소 지정 여부,v34안전 수칙 위반 처벌 및 단속 강화 필요 여부,v4이용종류,v4_1이용여부
0,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,2,3,4,4,4,5,5,0,0
1,2,1,3,1.0,0.0,0,1.0,5.0,2.0,1.0,...,5,4,4,4,4,4,5,4,0,0
2,1,4,5,0.0,1.0,0,2.0,1.0,3.0,1.0,...,5,2,1,5,4,4,5,5,0,0
3,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,0,0
4,1,2,5,0.0,1.0,0,2.0,4.0,3.0,1.0,...,5,1,1,5,5,2,5,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2,3,2,0.0,1.0,0,2.0,1.0,3.0,1.0,...,4,4,2,4,5,4,4,3,0,0
196,1,4,2,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,0,0
197,1,4,2,1.0,0.0,0,2.0,2.0,2.0,2.0,...,5,5,4,4,5,4,5,5,0,0
198,2,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,0,0
199,2,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,0,0

In [12]:
def v4(row):
    if row['v41이용종류'] ==1.0 :
        return 1
    if row['v42이용종류'] ==1.0 :
        return 2
    if row['v43이용종류'] ==1.0 :
        return 3

In [13]:
def v4_1(row):
    if row['v41이용종류'] ==1.0 :
        return 1
    if row['v42이용종류'] ==1.0 :
        return 1
    if row['v43이용종류'] ==1.0 :
        return 0

In [14]:
data['v4이용종류'] = data.apply(v4, axis=1)
data['v4_1이용여부'] = data.apply(v4_1, axis =1)
data

,v1성별,v2학년,v3소속대학,v41이용종류,v42이용종류,v43이용종류,v5이용목적,v6이용빈도,v7이용시간대,v8안전장비착용여부,...,v27음주 이용 사고 유발 가능성,v28보험 가입 의무화 필요성,v29인도 주행 허용 여부,v30특정 구간 속도 제한 여부,"v31번호판, 반사테이프 부착 의무화 여부",v32면허증 강화 필요성,v33반납 장소 지정 여부,v34안전 수칙 위반 처벌 및 단속 강화 필요 여부,v4이용종류,v4_1이용여부
0,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,2,3,4,4,4,5,5,3,0
1,2,1,3,1.0,0.0,0,1.0,5.0,2.0,1.0,...,5,4,4,4,4,4,5,4,1,1
2,1,4,5,0.0,1.0,0,2.0,1.0,3.0,1.0,...,5,2,1,5,4,4,5,5,2,1
3,1,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0
4,1,2,5,0.0,1.0,0,2.0,4.0,3.0,1.0,...,5,1,1,5,5,2,5,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2,3,2,0.0,1.0,0,2.0,1.0,3.0,1.0,...,4,4,2,4,5,4,4,3,2,1
196,1,4,2,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0
197,1,4,2,1.0,0.0,0,2.0,2.0,2.0,2.0,...,5,5,4,4,5,4,5,5,1,1
198,2,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0
199,2,4,5,0.0,0.0,1,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0

In [17]:
data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
v1성별,200.0,1.325000,0.469550,1.0,1.00,1.0,2.0,2.0
v2학년,200.0,2.650000,1.124197,1.0,2.00,3.0,4.0,4.0
v3소속대학,200.0,3.900000,1.526977,1.0,3.00,5.0,5.0,5.0
v41이용종류,198.0,0.237374,0.426552,0.0,0.00,0.0,0.0,1.0
v42이용종류,198.0,0.373737,0.485022,0.0,0.00,0.0,1.0,1.0
v43이용종류,200.0,0.475000,0.500628,0.0,0.00,0.0,1.0,1.0
v5이용목적,105.0,1.933333,1.076557,1.0,1.00,2.0,2.0,4.0
v6이용빈도,105.0,2.438095,1.480149,1.0,1.00,2.0,4.0,5.0
v7이용시간대,105.0,2.180952,0.743962,1.0,2.00,2.0,3.0,3.0
v8안전장비착용여부,105.0,1.514286,0.761000,1.0,1.00,1.0,2.0,3.0
v9보험가입여부,105.0,2.104762,0.535720,1.0,2.00,2.0,2.0,3.0
v10음주여부,103.0,1.174757,0.381616,1.0,1.00,1.0,1.0,2.0
v11사고경험,105.0,1.123810,0.330944,1.0,1.00,1.0,1.0,2.0
v12안전불안감,105.0,2.619048,1.138327,1.0,2.00,3.0,3.0,5.0
v13위험대상,105.0,1.866667,0.990985,1.0,1.00,2.0,2.0,4.0
v14위험장소,105.0,2.028571,1.104685,1.0,1.00,2.0,2.0,4.0
v15사고원인,105.0,2.895238,1.568462,1.0,2.00,2.0,4.0,6.0
v16안전여부,105.0,2.457143,0.909655,1.0,2.00,2.0,3.0,4.0
v17편리성,105.0,3.771429,1.094190,1.0,3.00,4.0,5.0,5.0
v18안전성,105.0,2.504762,1.075280,1.0,2.00,3.0,3.0,5.0
v19접근성,105.0,2.838095,1.352518,1.0,2.00,3.0,4.0,5.0
v20대여 및 반납,105.0,3.038095,1.307698,1.0,2.00,3.0,4.0,5.0
v21사고 목격 경험,105.0,1.371429,0.485504,1.0,1.00,1.0,2.0,2.0
v22보호장비 착용 필요도,105.0,3.980952,1.074002,1.0,4.00,4.0,5.0,5.0
v23위험수준,200.0,1.950000,1.045450,1.0,1.00,2.0,2.0,5.0
v24상해 가능성,200.0,4.335000,0.875562,1.0,4.00,5.0,5.0,5.0
v25보호장비 미착용 사고 위험 노출,200.0,4.325000,0.896321,1.0,4.00,5.0,5.0,5.0
v26보도 주행 보행자 충돌 위험성,200.0,4.370000,0.903983,1.0,4.00,5.0,5.0,5.0
v27음주 이용 사고 유발 가능성,200.0,4.660000,0.653095,2.0,4.75,5.0,5.0,5.0
v28보험 가입 의무화 필요성,200.0,3.435000,1.402000,1.0,2.00,4.0,5.0,5.0
v29인도 주행 허용 여부,200.0,2.495000,1.399919,1.0,1.00,2.0,4.0,5.0
v30특정 구간 속도 제한 여부,200.0,4.220000,0.857483,2.0,4.00,4.0,5.0,5.0
"v31번호판, 반사테이프 부착 의무화 여부",200.0,4.430000,0.733341,2.0,4.00,5.0,5.0,5.0
v32면허증 강화 필요성,200.0,4.290000,0.894371,2.0,4.00,5.0,5.0,5.0
v33반납 장소 지정 여부,200.0,4.490000,0.826630,1.0,4.00,5.0,5.0,5.0
v34안전 수칙 위반 처벌 및 단속 강화 필요 여부,200.0,4.370000,0.915034,1.0,4.00,5.0,5.0,5.0
v4이용종류,200.0,2.240000,0.809740,1.0,2.00,2.0,3.0,3.0
v4_1이용여부,200.0,0.525000,0.500628,0.0,0.00,1.0,1.0,1.0

In [192]:
data.drop(columns=['v41이용종류','v42이용종류','v43이용종류'], inplace=True)
data

,v1성별,v2학년,v3소속대학,v5이용목적,v6이용빈도,v7이용시간대,v8안전장비착용여부,v9보험가입여부,v10음주여부,v11사고경험,...,v27음주 이용 사고 유발 가능성,v28보험 가입 의무화 필요성,v29인도 주행 허용 여부,v30특정 구간 속도 제한 여부,"v31번호판, 반사테이프 부착 의무화 여부",v32면허증 강화 필요성,v33반납 장소 지정 여부,v34안전 수칙 위반 처벌 및 단속 강화 필요 여부,v4이용종류,v4_1이용여부
0,1,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,2,3,4,4,4,5,5,3,0
1,2,1,3,1.0,5.0,2.0,1.0,3.0,1.0,1.0,...,5,4,4,4,4,4,5,4,1,1
2,1,4,5,2.0,1.0,3.0,1.0,2.0,1.0,1.0,...,5,2,1,5,4,4,5,5,2,1
3,1,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0
4,1,2,5,2.0,4.0,3.0,1.0,2.0,1.0,1.0,...,5,1,1,5,5,2,5,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2,3,2,2.0,1.0,3.0,1.0,2.0,1.0,1.0,...,4,4,2,4,5,4,4,3,2,1
196,1,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0
197,1,4,2,2.0,2.0,2.0,2.0,2.0,1.0,1.0,...,5,5,4,4,5,4,5,5,1,1
198,2,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0
199,2,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0

In [193]:
from scipy.stats import ttest_ind

In [194]:
columns_to_test = data.columns[data.columns.get_loc("v5이용목적"):data.columns.get_loc("v34안전 수칙 위반 처벌 및 단속 강화 필요 여부") + 1]

In [195]:
data['v4_1이용여부'].unique()

array([0, 1])

In [196]:
use = data[data['v4_1이용여부'] ==1]
n_use = data[data['v4_1이용여부'] ==0]
results = []

In [197]:
for col in columns_to_test:
    m_values = use[col].dropna()
    f_values = n_use[col].dropna()

    if len(m_values) > 1 and len(f_values) > 1:
        t_stat, p_value = ttest_ind(m_values, f_values, equal_var=False)
        results.append({
            '항목': col,
            '이용자 평균': round(m_values.mean(), 3),
            '비이용자 평균': round(f_values.mean(), 3),
            'p값': round(p_value, 5),
            '유의한 차이': p_value < 0.05
        })

In [198]:
ttest_df = pd.DataFrame(results)
print(ttest_df)

                              항목  이용자 평균  비이용자 평균       p값  유의한 차이
0                        v23위험수준   2.171    1.705  0.00124    True
1                      v24상해 가능성   4.238    4.442  0.09507   False
2           v25보호장비 미착용 사고 위험 노출   4.152    4.516  0.00327    True
3            v26보도 주행 보행자 충돌 위험성   4.295    4.453  0.21193   False
4             v27음주 이용 사고 유발 가능성   4.610    4.716  0.24319   False
5               v28보험 가입 의무화 필요성   3.190    3.705  0.00903    True
6                 v29인도 주행 허용 여부   2.810    2.147  0.00068    True
7              v30특정 구간 속도 제한 여부   4.086    4.368  0.01939    True
8        v31번호판, 반사테이프 부착 의무화 여부   4.152    4.737  0.00000    True
9                  v32면허증 강화 필요성   4.000    4.611  0.00000    True
10                v33반납 장소 지정 여부   4.448    4.537  0.44158   False
11  v34안전 수칙 위반 처벌 및 단속 강화 필요 여부   4.019    4.758  0.00000    True

In [199]:
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [200]:
use_levels = sorted(data['v4이용종류'].dropna().unique())

In [201]:
significant_columns = []

In [ ]:
for col in columns_to_test:
    groups = [data[data['v4이용종류'] == use][col].dropna() for use in use_levels]
    if all(len(g) > 1 for g in groups):
        f_stat, p_value = f_oneway(*groups)
        if p_value < 0.05:
            print(f" [ANOVA 유의] {col} | F={round(f_stat, 4)}, p={round(p_value, 5)}")
            significant_columns.append(col)
for col in significant_columns:
    print(f"\n [Tukey HSD 결과] {col}")
    tukey = pairwise_tukeyhsd(endog=data[col].dropna(), groups=data['v4이용종류'][data[col].notna()], alpha=0.05)
    print(tukey.summary())

 [ANOVA 유의] v23위험수준 | F=11.1096, p=3e-05
 [ANOVA 유의] v24상해 가능성 | F=12.5093, p=1e-05
 [ANOVA 유의] v25보호장비 미착용 사고 위험 노출 | F=13.1605, p=0.0
 [ANOVA 유의] v28보험 가입 의무화 필요성 | F=3.9634, p=0.02053
 [ANOVA 유의] v29인도 주행 허용 여부 | F=15.8834, p=0.0
 [ANOVA 유의] v30특정 구간 속도 제한 여부 | F=3.4562, p=0.03347
 [ANOVA 유의] v31번호판, 반사테이프 부착 의무화 여부 | F=18.8845, p=0.0
 [ANOVA 유의] v32면허증 강화 필요성 | F=16.1665, p=0.0
 [ANOVA 유의] v34안전 수칙 위반 처벌 및 단속 강화 필요 여부 | F=19.5536, p=0.0

In [203]:
for col in significant_columns:
    print(f"\n [Tukey HSD 결과] {col}")
    tukey = pairwise_tukeyhsd(endog=data[col].dropna(), groups=data['v4이용종류'][data[col].notna()], alpha=0.05)
    print(tukey.summary())

 [Tukey HSD 결과] v23위험수준
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2    0.657 0.0027  0.1953  1.1187   True
     1      3  -0.1032 0.8303 -0.5227  0.3162  False
     2      3  -0.7603    0.0 -1.1522 -0.3683   True
----------------------------------------------------

 [Tukey HSD 결과] v24상해 가능성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   -0.763    0.0 -1.1472 -0.3788   True
     1      3  -0.2175  0.307 -0.5666  0.1316  False
     2      3   0.5456 0.0003  0.2194  0.8718   True
----------------------------------------------------

 [Tukey HSD 결과] v25보호장비 미착용 사고 위험 노출
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.6871 0.0002 -1.0792 -0.2949   True
     1      3  -0.0161 0.9937 -0.3725  0.3402  False
     2      3    0.671    0.0   0.338  1.0039   True
----------------------------------------------------

 [Tukey HSD 결과] v28보험 가입 의무화 필요성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.2715  0.577 -0.9118 0.3689  False
     1      3   0.3648 0.3023  -0.217 0.9467  False
     2      3   0.6363 0.0171  0.0926   1.18   True
---------------------------------------------------

 [Tukey HSD 결과] v29인도 주행 허용 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -1.1152 0.0001 -1.7203   -0.51   True
     1      3  -1.2782    0.0  -1.828 -0.7283   True
     2      3   -0.163 0.7345 -0.6768  0.3508  False
----------------------------------------------------

 [Tukey HSD 결과] v30특정 구간 속도 제한 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.1937 0.4755 -0.1989 0.5863  False
     1      3   0.3897 0.0285  0.0329 0.7464   True
     2      3    0.196 0.3488 -0.1373 0.5294  False
---------------------------------------------------

 [Tukey HSD 결과] v31번호판, 반사테이프 부착 의무화 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.0833 0.8047 -0.2297 0.3962  False
     1      3   0.6305    0.0  0.3461 0.9148   True
     2      3   0.5472    0.0  0.2815 0.8129   True
---------------------------------------------------

 [Tukey HSD 결과] v32면허증 강화 필요성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.3852 0.0507 -0.7713  0.001  False
     1      3   0.3978 0.0219  0.0469 0.7486   True
     2      3   0.7829    0.0  0.4551 1.1108   True
---------------------------------------------------

 [Tukey HSD 결과] v34안전 수칙 위반 처벌 및 단속 강화 필요 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.1196 0.7488 -0.5089 0.2698  False
     1      3   0.6728    0.0   0.319 1.0266   True
     2      3   0.7924    0.0  0.4618  1.123   True
---------------------------------------------------

In [242]:
significant_columns = []
use_levels = data['v4이용종류'].dropna().unique()
for col in columns_to_test:
    groups = [data[data['v4이용종류'] == use][col].dropna() for use in use_levels]
    if all(len(g) > 1 for g in groups):
        f_stat, p_value = f_oneway(*groups)
        if p_value < 0.05:
            significant_columns.append(col)

# 박스플롯 (산점도 제거)
for col in significant_columns:
    fig = px.box(data, x="v4이용종류", y=col, points=False,
                 labels={"v4이용종류": "이용종류", col: col})
    fig.show()

In [241]:
data['이용종류라벨'] = data['v4이용종류'].map({1: '전동 킥보드', 2: '전기 자전거', 3: '없음'})

# ANOVA 분석 + 유의한 열 추출
significant_columns = []
use_levels = data['v4이용종류'].dropna().unique()

for col in columns_to_test:
    groups = [data[data['v4이용종류'] == use][col].dropna() for use in use_levels]
    if all(len(g) > 1 for g in groups):
        f_stat, p_value = f_oneway(*groups)
        if p_value < 0.05:
            significant_columns.append(col)

# 박스플롯 생성 (산점도 제거)
for col in significant_columns:
    fig = px.box(
        data,
        x="이용종류라벨",
        y=col,
        points=False,
        labels={"이용종류라벨": "이용종류", col: col}
    )
    fig.show()

In [248]:
from scipy.stats import chi2_contingency
import numpy as np

In [246]:
chi2_results = []
for col in columns_to_test:
    ct = pd.crosstab(data['v4_1이용여부'], data[col])
    if ct.shape[0] > 1 and ct.shape[1] > 1:
        chi2, p, dof, expected = chi2_contingency(ct)
        chi2_results.append({
            '변수': col,
            '카이제곱 통계량': round(chi2, 4),
            'p값': round(p, 5),
            '자유도': dof,
            '유의함': p < 0.05
        })

# 데이터프레임 변환 및 정렬
chi2_df = pd.DataFrame(chi2_results).sort_values(by='p값').reset_index(drop=True)
chi2_df

                              변수  카이제곱 통계량       p값  자유도    유의함
0                  v32면허증 강화 필요성   27.9082  0.00000    3   True
1   v34안전 수칙 위반 처벌 및 단속 강화 필요 여부   36.2368  0.00000    4   True
2        v31번호판, 반사테이프 부착 의무화 여부   33.2764  0.00000    3   True
3               v28보험 가입 의무화 필요성   26.8394  0.00002    4   True
4                 v29인도 주행 허용 여부   20.1522  0.00047    4   True
5                        v23위험수준   16.5288  0.00239    4   True
6           v25보호장비 미착용 사고 위험 노출   11.1937  0.02447    4   True
7              v30특정 구간 속도 제한 여부    9.1241  0.02769    3   True
8                 v33반납 장소 지정 여부   10.3064  0.03557    4   True
9             v27음주 이용 사고 유발 가능성    8.4015  0.03840    3   True
10           v26보도 주행 보행자 충돌 위험성    7.0622  0.13264    4  False
11                     v24상해 가능성    4.0807  0.39520    4  False

In [249]:
results = []
for col in columns_to_test:
    table = pd.crosstab(data['v4_1이용여부'], data[col])
    if table.shape[0] > 1 and table.shape[1] > 1:
        chi2, p, dof, expected = chi2_contingency(table)
        results.append({
            '변수': col,
            '카이제곱 통계량': chi2,
            'p값': p,
            '-log(p값)': -np.log10(p) if p > 0 else 0,
            '유의함': p < 0.05
        })

# 데이터프레임으로 변환
df = pd.DataFrame(results)
sig_df = df[df['유의함'] == True].sort_values(by='p값')

# 시각화
fig = px.bar(sig_df, x='변수', y='-log(p값)', color='유의함', text='p값',
             title='v4_1이용여부와 유의한 변수들 (카이제곱 검정 시각화)',
             labels={'-log(p값)': '-log(p-value)', '변수': '변수명'})
fig.update_layout(xaxis_tickangle=45)
fig.show()

In [250]:
results = []
for col in columns_to_test:
    table = pd.crosstab(data['v4_1이용여부'], data[col])
    if table.shape[0] > 1 and table.shape[1] > 1:
        chi2, p, dof, _ = chi2_contingency(table)
        results.append({
            '변수': col,
            '카이제곱 통계량': chi2,
            'p값': p,
            '-log(p값)': -np.log10(p) if p > 0 else 0,
            '유의함': p < 0.05
        })

# 데이터프레임으로 정리
df = pd.DataFrame(results)
sig_df = df[df['유의함']].sort_values(by='p값')

# 시각화
fig = px.bar(
    sig_df,
    x='변수',
    y='-log(p값)',
    text=sig_df['p값'].apply(lambda x: f"{x:.4f}"),
    title='v4_1이용여부와 유의한 변수들 (카이제곱 검정 시각화)',
    labels={'-log(p값)': '-log(p-value)', '변수': '변수명'},
    color='유의함'
)
fig.update_layout(xaxis_tickangle=45)
fig.show()

In [204]:
grade_levels = sorted(data['v2학년'].dropna().unique())

In [205]:
significant_columns = []

In [206]:
for col in columns_to_test:
    groups = [data[data['v2학년'] == grade][col].dropna() for grade in grade_levels]
    if all(len(g) > 1 for g in groups):
        f_stat, p_value = f_oneway(*groups)
        if p_value < 0.05:
            print(f" [ANOVA 유의] {col} | F={round(f_stat, 4)}, p={round(p_value, 5)}")
            significant_columns.append(col)

 [ANOVA 유의] v5이용목적 | F=6.8927, p=0.00029
 [ANOVA 유의] v6이용빈도 | F=15.707, p=0.0
 [ANOVA 유의] v7이용시간대 | F=5.5235, p=0.00149
 [ANOVA 유의] v8안전장비착용여부 | F=13.0718, p=0.0
 [ANOVA 유의] v9보험가입여부 | F=12.6391, p=0.0
 [ANOVA 유의] v11사고경험 | F=5.8522, p=0.001
 [ANOVA 유의] v14위험장소 | F=3.6723, p=0.01471
 [ANOVA 유의] v15사고원인 | F=3.4461, p=0.01952
 [ANOVA 유의] v17편리성 | F=7.4909, p=0.00014
 [ANOVA 유의] v18안전성 | F=9.5253, p=1e-05
 [ANOVA 유의] v20대여 및 반납 | F=7.3658, p=0.00016
 [ANOVA 유의] v21사고 목격 경험 | F=3.8376, p=0.01197
 [ANOVA 유의] v22보호장비 착용 필요도 | F=4.0709, p=0.00895
 [ANOVA 유의] v23위험수준 | F=3.6085, p=0.01433
 [ANOVA 유의] v27음주 이용 사고 유발 가능성 | F=6.0334, p=0.0006
 [ANOVA 유의] v28보험 가입 의무화 필요성 | F=6.6875, p=0.00025
 [ANOVA 유의] v29인도 주행 허용 여부 | F=10.436, p=0.0
 [ANOVA 유의] v30특정 구간 속도 제한 여부 | F=7.9568, p=5e-05
 [ANOVA 유의] v31번호판, 반사테이프 부착 의무화 여부 | F=5.4476, p=0.00128
 [ANOVA 유의] v32면허증 강화 필요성 | F=4.0533, p=0.008
 [ANOVA 유의] v33반납 장소 지정 여부 | F=4.5128, p=0.00437
 [ANOVA 유의] v34안전 수칙 위반 처벌 및 단속 강화 필요 여부 | F=4.4897, p=0.00451

In [207]:
for col in significant_columns:
    print(f"\n [Tukey HSD 결과] {col}")
    tukey = pairwise_tukeyhsd(endog=data[col].dropna(), groups=data['v2학년'][data[col].notna()], alpha=0.05)
    print(tukey.summary())

 [Tukey HSD 결과] v5이용목적
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.2459 0.8099 -0.9676  0.4757  False
     1      3   0.7037 0.0519 -0.0039  1.4113  False
     1      4  -0.4644 0.3301 -1.1788    0.25  False
     2      3   0.9496 0.0047   0.228  1.6713   True
     2      4  -0.2185 0.8617 -0.9467  0.5098  False
     3      4  -1.1681 0.0003 -1.8825 -0.4537   True
----------------------------------------------------

 [Tukey HSD 결과] v6이용빈도
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.2874 0.8377 -1.1867  0.6119  False
     1      3  -1.8519    0.0 -2.7337   -0.97   True
     1      4  -1.7151    0.0 -2.6053 -0.8249   True
     2      3  -1.5644 0.0001 -2.4637 -0.6652   True
     2      4  -1.4277 0.0005 -2.3352 -0.5201   True
     3      4   0.1368  0.978 -0.7535   1.027  False
----------------------------------------------------

 [Tukey HSD 결과] v7이용시간대
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   0.2311 0.6345 -0.2762  0.7384  False
     1      3   0.7407  0.001  0.2433  1.2382   True
     1      4    0.188 0.7623 -0.3142  0.6903  False
     2      3   0.5096 0.0485  0.0023   1.017   True
     2      4  -0.0431 0.9962 -0.5551  0.4689  False
     3      4  -0.5527  0.025  -1.055 -0.0505   True
----------------------------------------------------

 [Tukey HSD 결과] v8안전장비착용여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   0.4059 0.1218 -0.0693  0.8811  False
     1      3   1.0741    0.0  0.6081    1.54   True
     1      4   0.2721 0.4348 -0.1984  0.7425  False
     2      3   0.6681 0.0022  0.1929  1.1434   True
     2      4  -0.1338 0.8852 -0.6134  0.3457  False
     3      4   -0.802 0.0001 -1.2724 -0.3316   True
----------------------------------------------------

 [Tukey HSD 결과] v9보험가입여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.5156 0.0007 -0.8516 -0.1795   True
     1      3  -0.7407    0.0 -1.0703 -0.4112   True
     1      4  -0.5556 0.0002 -0.8883 -0.2228   True
     2      3  -0.2252 0.3035 -0.5613  0.1109  False
     2      4    -0.04 0.9898 -0.3792  0.2992  False
     3      4   0.1852 0.4691 -0.1475  0.5179  False
----------------------------------------------------

 [Tukey HSD 결과] v11사고경험
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.1852 0.1438 -0.4099  0.0396  False
     1      3   0.1111 0.5543 -0.1093  0.3315  False
     1      4  -0.1852 0.1374 -0.4077  0.0373  False
     2      3   0.2963 0.0046  0.0716   0.521   True
     2      4      0.0    1.0 -0.2268  0.2268  False
     3      4  -0.2963 0.0041 -0.5188 -0.0738   True
----------------------------------------------------

 [Tukey HSD 결과] v14위험장소
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2    0.597 0.1872 -0.1747  1.3688  False
     1      3   0.0741 0.9941 -0.6827  0.8309  False
     1      4   -0.386 0.5525 -1.1501   0.378  False
     2      3   -0.523 0.2937 -1.2947  0.2488  False
     2      4  -0.9831 0.0073  -1.762 -0.2042   True
     3      4  -0.4601 0.3985 -1.2241  0.3039  False
----------------------------------------------------

 [Tukey HSD 결과] v15사고원인
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.5778  0.519 -0.5213 1.6769  False
     1      3   0.8148 0.2043  -0.263 1.8926  False
     1      4   1.3162  0.011  0.2281 2.4043   True
     2      3    0.237 0.9427 -0.8621 1.3362  False
     2      4   0.7385 0.3091 -0.3708 1.8477  False
     3      4   0.5014 0.6259 -0.5867 1.5895  False
---------------------------------------------------

 [Tukey HSD 결과] v17편리성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.7585 0.0378 -1.4866 -0.0304   True
     1      3  -1.0741 0.0009 -1.7881 -0.3601   True
     1      4  -1.1724 0.0003 -1.8932 -0.4516   True
     2      3  -0.3156 0.6706 -1.0437  0.4126  False
     2      4  -0.4138 0.4586 -1.1487   0.321  False
     3      4  -0.0983 0.9844 -0.8191  0.6225  False
----------------------------------------------------

 [Tukey HSD 결과] v18안전성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.3081  0.658 -1.0066  0.3903  False
     1      3  -1.1481 0.0002 -1.8331 -0.4632   True
     1      4  -1.1097 0.0003 -1.8012 -0.4182   True
     2      3    -0.84 0.0117 -1.5385 -0.1415   True
     2      4  -0.8015 0.0192 -1.5064 -0.0966   True
     3      4   0.0385 0.9989  -0.653  0.7299  False
----------------------------------------------------

 [Tukey HSD 결과] v20대여 및 반납
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.6578 0.2056 -1.5293  0.2137  False
     1      3  -0.7778  0.088 -1.6324  0.0768  False
     1      4   -1.547 0.0001 -2.4098 -0.6842   True
     2      3    -0.12  0.984 -0.9915  0.7515  False
     2      4  -0.8892 0.0465 -1.7688 -0.0097   True
     3      4  -0.7692 0.0982  -1.632  0.0935  False
----------------------------------------------------

 [Tukey HSD 결과] v21사고 목격 경험
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.3156 0.0769  -0.654  0.0229  False
     1      3  -0.0741  0.937 -0.4059  0.2578  False
     1      4  -0.3632 0.0281 -0.6983 -0.0282   True
     2      3   0.2415 0.2502  -0.097  0.5799  False
     2      4  -0.0477 0.9833 -0.3892  0.2939  False
     3      4  -0.2892 0.1158 -0.6242  0.0459  False
----------------------------------------------------

 [Tukey HSD 결과] v22보호장비 착용 필요도
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.4044 0.4926 -0.3419 1.1508  False
     1      3    0.963 0.0047  0.2311 1.6948   True
     1      4   0.3291 0.6512 -0.4098 1.0679  False
     2      3   0.5585 0.2122 -0.1878 1.3049  False
     2      4  -0.0754 0.9937 -0.8286 0.6778  False
     3      4  -0.6339 0.1192 -1.3728  0.105  False
---------------------------------------------------

 [Tukey HSD 결과] v23위험수준
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   0.5063 0.0918 -0.0535  1.0662  False
     1      3  -0.0877 0.9782 -0.6555  0.4801  False
     1      4  -0.0311 0.9988  -0.566  0.5038  False
     2      3   -0.594 0.0247 -1.1339 -0.0542   True
     2      4  -0.5374 0.0321 -1.0425 -0.0323   True
     3      4   0.0566 0.9919 -0.4573  0.5705  False
----------------------------------------------------

 [Tukey HSD 결과] v27음주 이용 사고 유발 가능성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.2873 0.1365 -0.6311 0.0564  False
     1      3  -0.1541 0.6618 -0.5028 0.1945  False
     1      4   0.1959 0.4123 -0.1325 0.5243  False
     2      3   0.1332 0.7254 -0.1983 0.4647  False
     2      4   0.4832 0.0004  0.1731 0.7933   True
     3      4     0.35 0.0231  0.0345 0.6656   True
---------------------------------------------------

 [Tukey HSD 결과] v28보험 가입 의무화 필요성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2    0.099 0.9853 -0.6355  0.8336  False
     1      3   0.3326 0.6547 -0.4124  1.0777  False
     1      4  -0.7384 0.0349 -1.4402 -0.0366   True
     2      3   0.2336 0.8281 -0.4747   0.942  False
     2      4  -0.8374 0.0068 -1.5001 -0.1747   True
     3      4   -1.071 0.0003 -1.7453 -0.3967   True
----------------------------------------------------

 [Tukey HSD 결과] v29인도 주행 허용 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.9927 0.0023 -1.7078 -0.2776   True
     1      3  -0.5054 0.2737 -1.2308  0.2199  False
     1      4  -1.3895    0.0 -2.0727 -0.7062   True
     2      3   0.4872  0.262 -0.2023  1.1768  False
     2      4  -0.3968 0.3846 -1.0419  0.2484  False
     3      4   -0.884 0.0033 -1.5404 -0.2276   True
----------------------------------------------------

 [Tukey HSD 결과] v30특정 구간 속도 제한 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.2795 0.3663 -0.1659 0.7249  False
     1      3   0.6025 0.0037  0.1508 1.0542   True
     1      4   0.7356 0.0001  0.3101 1.1611   True
     2      3    0.323 0.2113 -0.1065 0.7524  False
     2      4   0.4561  0.019  0.0543 0.8579   True
     3      4   0.1332 0.8334 -0.2757  0.542  False
---------------------------------------------------

 [Tukey HSD 결과] v31번호판, 반사테이프 부착 의무화 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.5712  0.001  0.1836 0.9588   True
     1      3    0.398  0.046  0.0049 0.7911   True
     1      4   0.4673 0.0069  0.0971 0.8376   True
     2      3  -0.1732 0.6271 -0.5469 0.2005  False
     2      4  -0.1039  0.868 -0.4535 0.2458  False
     3      4   0.0693 0.9578 -0.2865 0.4251  False
---------------------------------------------------

 [Tukey HSD 결과] v32면허증 강화 필요성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.2732 0.4499 -0.2042 0.7506  False
     1      3     0.52 0.0299  0.0358 1.0042   True
     1      4    0.557 0.0097  0.1009 1.0132   True
     2      3   0.2468 0.5076 -0.2136 0.7072  False
     2      4   0.2839 0.3224 -0.1468 0.7146  False
     3      4   0.0371 0.9963 -0.4012 0.4753  False
---------------------------------------------------

 [Tukey HSD 결과] v33반납 장소 지정 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.2605 0.4188 -0.1793 0.7003  False
     1      3   0.1422 0.8421 -0.3039 0.5883  False
     1      4   0.5547 0.0042  0.1345 0.9749   True
     2      3  -0.1183 0.8879 -0.5424 0.3058  False
     2      4   0.2942 0.2225 -0.1026  0.691  False
     3      4   0.4125 0.0432  0.0088 0.8162   True
---------------------------------------------------

 [Tukey HSD 결과] v34안전 수칙 위반 처벌 및 단속 강화 필요 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.2156 0.6606 -0.2713 0.7025  False
     1      3   0.4224 0.1224 -0.0714 0.9163  False
     1      4   0.6208 0.0037  0.1556  1.086   True
     2      3   0.2068 0.6644 -0.2627 0.6763  False
     2      4   0.4052 0.0823 -0.0341 0.8444  False
     3      4   0.1984 0.6591 -0.2486 0.6453  False
---------------------------------------------------

In [208]:
univ_levels = sorted(data['v3소속대학'].dropna().unique())

In [209]:
significant_column = []

In [210]:
for col in columns_to_test:
    groups = [data[data['v3소속대학'] == univ][col].dropna() for univ in univ_levels]
    if all(len(g) > 1 for g in groups):
        f_stat, p_value = f_oneway(*groups)
        if p_value < 0.05:
            print(f" [ANOVA 유의] {col} | F={round(f_stat, 4)}, p={round(p_value, 5)}")
            significant_columns.append(col)

 [ANOVA 유의] v5이용목적 | F=8.0104, p=1e-05
 [ANOVA 유의] v6이용빈도 | F=5.2737, p=0.00068
 [ANOVA 유의] v7이용시간대 | F=2.9483, p=0.02381
 [ANOVA 유의] v8안전장비착용여부 | F=5.4203, p=0.00054
 [ANOVA 유의] v9보험가입여부 | F=7.8671, p=1e-05
 [ANOVA 유의] v10음주여부 | F=5.9621, p=0.00025
 [ANOVA 유의] v11사고경험 | F=3.3034, p=0.0138
 [ANOVA 유의] v12안전불안감 | F=4.0766, p=0.0042
 [ANOVA 유의] v14위험장소 | F=5.8421, p=0.00029
 [ANOVA 유의] v19접근성 | F=24.0706, p=0.0
 [ANOVA 유의] v20대여 및 반납 | F=8.5603, p=1e-05
 [ANOVA 유의] v21사고 목격 경험 | F=5.3942, p=0.00056
 [ANOVA 유의] v23위험수준 | F=4.7942, p=0.00104
 [ANOVA 유의] v25보호장비 미착용 사고 위험 노출 | F=3.5212, p=0.00843
 [ANOVA 유의] v27음주 이용 사고 유발 가능성 | F=4.6042, p=0.00142
 [ANOVA 유의] v29인도 주행 허용 여부 | F=12.7916, p=0.0
 [ANOVA 유의] v30특정 구간 속도 제한 여부 | F=4.9951, p=0.00075
 [ANOVA 유의] v33반납 장소 지정 여부 | F=3.3233, p=0.01165

In [211]:
for col in significant_columns:
    print(f"\n [Tukey HSD 결과] {col}")
    tukey = pairwise_tukeyhsd(endog=data[col].dropna(), groups=data['v2학년'][data[col].notna()], alpha=0.05)
    print(tukey.summary())

 [Tukey HSD 결과] v5이용목적
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.2459 0.8099 -0.9676  0.4757  False
     1      3   0.7037 0.0519 -0.0039  1.4113  False
     1      4  -0.4644 0.3301 -1.1788    0.25  False
     2      3   0.9496 0.0047   0.228  1.6713   True
     2      4  -0.2185 0.8617 -0.9467  0.5098  False
     3      4  -1.1681 0.0003 -1.8825 -0.4537   True
----------------------------------------------------

 [Tukey HSD 결과] v6이용빈도
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.2874 0.8377 -1.1867  0.6119  False
     1      3  -1.8519    0.0 -2.7337   -0.97   True
     1      4  -1.7151    0.0 -2.6053 -0.8249   True
     2      3  -1.5644 0.0001 -2.4637 -0.6652   True
     2      4  -1.4277 0.0005 -2.3352 -0.5201   True
     3      4   0.1368  0.978 -0.7535   1.027  False
----------------------------------------------------

 [Tukey HSD 결과] v7이용시간대
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   0.2311 0.6345 -0.2762  0.7384  False
     1      3   0.7407  0.001  0.2433  1.2382   True
     1      4    0.188 0.7623 -0.3142  0.6903  False
     2      3   0.5096 0.0485  0.0023   1.017   True
     2      4  -0.0431 0.9962 -0.5551  0.4689  False
     3      4  -0.5527  0.025  -1.055 -0.0505   True
----------------------------------------------------

 [Tukey HSD 결과] v8안전장비착용여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   0.4059 0.1218 -0.0693  0.8811  False
     1      3   1.0741    0.0  0.6081    1.54   True
     1      4   0.2721 0.4348 -0.1984  0.7425  False
     2      3   0.6681 0.0022  0.1929  1.1434   True
     2      4  -0.1338 0.8852 -0.6134  0.3457  False
     3      4   -0.802 0.0001 -1.2724 -0.3316   True
----------------------------------------------------

 [Tukey HSD 결과] v9보험가입여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.5156 0.0007 -0.8516 -0.1795   True
     1      3  -0.7407    0.0 -1.0703 -0.4112   True
     1      4  -0.5556 0.0002 -0.8883 -0.2228   True
     2      3  -0.2252 0.3035 -0.5613  0.1109  False
     2      4    -0.04 0.9898 -0.3792  0.2992  False
     3      4   0.1852 0.4691 -0.1475  0.5179  False
----------------------------------------------------

 [Tukey HSD 결과] v11사고경험
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.1852 0.1438 -0.4099  0.0396  False
     1      3   0.1111 0.5543 -0.1093  0.3315  False
     1      4  -0.1852 0.1374 -0.4077  0.0373  False
     2      3   0.2963 0.0046  0.0716   0.521   True
     2      4      0.0    1.0 -0.2268  0.2268  False
     3      4  -0.2963 0.0041 -0.5188 -0.0738   True
----------------------------------------------------

 [Tukey HSD 결과] v14위험장소
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2    0.597 0.1872 -0.1747  1.3688  False
     1      3   0.0741 0.9941 -0.6827  0.8309  False
     1      4   -0.386 0.5525 -1.1501   0.378  False
     2      3   -0.523 0.2937 -1.2947  0.2488  False
     2      4  -0.9831 0.0073  -1.762 -0.2042   True
     3      4  -0.4601 0.3985 -1.2241  0.3039  False
----------------------------------------------------

 [Tukey HSD 결과] v15사고원인
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.5778  0.519 -0.5213 1.6769  False
     1      3   0.8148 0.2043  -0.263 1.8926  False
     1      4   1.3162  0.011  0.2281 2.4043   True
     2      3    0.237 0.9427 -0.8621 1.3362  False
     2      4   0.7385 0.3091 -0.3708 1.8477  False
     3      4   0.5014 0.6259 -0.5867 1.5895  False
---------------------------------------------------

 [Tukey HSD 결과] v17편리성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.7585 0.0378 -1.4866 -0.0304   True
     1      3  -1.0741 0.0009 -1.7881 -0.3601   True
     1      4  -1.1724 0.0003 -1.8932 -0.4516   True
     2      3  -0.3156 0.6706 -1.0437  0.4126  False
     2      4  -0.4138 0.4586 -1.1487   0.321  False
     3      4  -0.0983 0.9844 -0.8191  0.6225  False
----------------------------------------------------

 [Tukey HSD 결과] v18안전성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.3081  0.658 -1.0066  0.3903  False
     1      3  -1.1481 0.0002 -1.8331 -0.4632   True
     1      4  -1.1097 0.0003 -1.8012 -0.4182   True
     2      3    -0.84 0.0117 -1.5385 -0.1415   True
     2      4  -0.8015 0.0192 -1.5064 -0.0966   True
     3      4   0.0385 0.9989  -0.653  0.7299  False
----------------------------------------------------

 [Tukey HSD 결과] v20대여 및 반납
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.6578 0.2056 -1.5293  0.2137  False
     1      3  -0.7778  0.088 -1.6324  0.0768  False
     1      4   -1.547 0.0001 -2.4098 -0.6842   True
     2      3    -0.12  0.984 -0.9915  0.7515  False
     2      4  -0.8892 0.0465 -1.7688 -0.0097   True
     3      4  -0.7692 0.0982  -1.632  0.0935  False
----------------------------------------------------

 [Tukey HSD 결과] v21사고 목격 경험
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.3156 0.0769  -0.654  0.0229  False
     1      3  -0.0741  0.937 -0.4059  0.2578  False
     1      4  -0.3632 0.0281 -0.6983 -0.0282   True
     2      3   0.2415 0.2502  -0.097  0.5799  False
     2      4  -0.0477 0.9833 -0.3892  0.2939  False
     3      4  -0.2892 0.1158 -0.6242  0.0459  False
----------------------------------------------------

 [Tukey HSD 결과] v22보호장비 착용 필요도
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.4044 0.4926 -0.3419 1.1508  False
     1      3    0.963 0.0047  0.2311 1.6948   True
     1      4   0.3291 0.6512 -0.4098 1.0679  False
     2      3   0.5585 0.2122 -0.1878 1.3049  False
     2      4  -0.0754 0.9937 -0.8286 0.6778  False
     3      4  -0.6339 0.1192 -1.3728  0.105  False
---------------------------------------------------

 [Tukey HSD 결과] v23위험수준
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   0.5063 0.0918 -0.0535  1.0662  False
     1      3  -0.0877 0.9782 -0.6555  0.4801  False
     1      4  -0.0311 0.9988  -0.566  0.5038  False
     2      3   -0.594 0.0247 -1.1339 -0.0542   True
     2      4  -0.5374 0.0321 -1.0425 -0.0323   True
     3      4   0.0566 0.9919 -0.4573  0.5705  False
----------------------------------------------------

 [Tukey HSD 결과] v27음주 이용 사고 유발 가능성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.2873 0.1365 -0.6311 0.0564  False
     1      3  -0.1541 0.6618 -0.5028 0.1945  False
     1      4   0.1959 0.4123 -0.1325 0.5243  False
     2      3   0.1332 0.7254 -0.1983 0.4647  False
     2      4   0.4832 0.0004  0.1731 0.7933   True
     3      4     0.35 0.0231  0.0345 0.6656   True
---------------------------------------------------

 [Tukey HSD 결과] v28보험 가입 의무화 필요성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2    0.099 0.9853 -0.6355  0.8336  False
     1      3   0.3326 0.6547 -0.4124  1.0777  False
     1      4  -0.7384 0.0349 -1.4402 -0.0366   True
     2      3   0.2336 0.8281 -0.4747   0.942  False
     2      4  -0.8374 0.0068 -1.5001 -0.1747   True
     3      4   -1.071 0.0003 -1.7453 -0.3967   True
----------------------------------------------------

 [Tukey HSD 결과] v29인도 주행 허용 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.9927 0.0023 -1.7078 -0.2776   True
     1      3  -0.5054 0.2737 -1.2308  0.2199  False
     1      4  -1.3895    0.0 -2.0727 -0.7062   True
     2      3   0.4872  0.262 -0.2023  1.1768  False
     2      4  -0.3968 0.3846 -1.0419  0.2484  False
     3      4   -0.884 0.0033 -1.5404 -0.2276   True
----------------------------------------------------

 [Tukey HSD 결과] v30특정 구간 속도 제한 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.2795 0.3663 -0.1659 0.7249  False
     1      3   0.6025 0.0037  0.1508 1.0542   True
     1      4   0.7356 0.0001  0.3101 1.1611   True
     2      3    0.323 0.2113 -0.1065 0.7524  False
     2      4   0.4561  0.019  0.0543 0.8579   True
     3      4   0.1332 0.8334 -0.2757  0.542  False
---------------------------------------------------

 [Tukey HSD 결과] v31번호판, 반사테이프 부착 의무화 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.5712  0.001  0.1836 0.9588   True
     1      3    0.398  0.046  0.0049 0.7911   True
     1      4   0.4673 0.0069  0.0971 0.8376   True
     2      3  -0.1732 0.6271 -0.5469 0.2005  False
     2      4  -0.1039  0.868 -0.4535 0.2458  False
     3      4   0.0693 0.9578 -0.2865 0.4251  False
---------------------------------------------------

 [Tukey HSD 결과] v32면허증 강화 필요성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.2732 0.4499 -0.2042 0.7506  False
     1      3     0.52 0.0299  0.0358 1.0042   True
     1      4    0.557 0.0097  0.1009 1.0132   True
     2      3   0.2468 0.5076 -0.2136 0.7072  False
     2      4   0.2839 0.3224 -0.1468 0.7146  False
     3      4   0.0371 0.9963 -0.4012 0.4753  False
---------------------------------------------------

 [Tukey HSD 결과] v33반납 장소 지정 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.2605 0.4188 -0.1793 0.7003  False
     1      3   0.1422 0.8421 -0.3039 0.5883  False
     1      4   0.5547 0.0042  0.1345 0.9749   True
     2      3  -0.1183 0.8879 -0.5424 0.3058  False
     2      4   0.2942 0.2225 -0.1026  0.691  False
     3      4   0.4125 0.0432  0.0088 0.8162   True
---------------------------------------------------

 [Tukey HSD 결과] v34안전 수칙 위반 처벌 및 단속 강화 필요 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.2156 0.6606 -0.2713 0.7025  False
     1      3   0.4224 0.1224 -0.0714 0.9163  False
     1      4   0.6208 0.0037  0.1556  1.086   True
     2      3   0.2068 0.6644 -0.2627 0.6763  False
     2      4   0.4052 0.0823 -0.0341 0.8444  False
     3      4   0.1984 0.6591 -0.2486 0.6453  False
---------------------------------------------------

 [Tukey HSD 결과] v5이용목적
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.2459 0.8099 -0.9676  0.4757  False
     1      3   0.7037 0.0519 -0.0039  1.4113  False
     1      4  -0.4644 0.3301 -1.1788    0.25  False
     2      3   0.9496 0.0047   0.228  1.6713   True
     2      4  -0.2185 0.8617 -0.9467  0.5098  False
     3      4  -1.1681 0.0003 -1.8825 -0.4537   True
----------------------------------------------------

 [Tukey HSD 결과] v6이용빈도
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.2874 0.8377 -1.1867  0.6119  False
     1      3  -1.8519    0.0 -2.7337   -0.97   True
     1      4  -1.7151    0.0 -2.6053 -0.8249   True
     2      3  -1.5644 0.0001 -2.4637 -0.6652   True
     2      4  -1.4277 0.0005 -2.3352 -0.5201   True
     3      4   0.1368  0.978 -0.7535   1.027  False
----------------------------------------------------

 [Tukey HSD 결과] v7이용시간대
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   0.2311 0.6345 -0.2762  0.7384  False
     1      3   0.7407  0.001  0.2433  1.2382   True
     1      4    0.188 0.7623 -0.3142  0.6903  False
     2      3   0.5096 0.0485  0.0023   1.017   True
     2      4  -0.0431 0.9962 -0.5551  0.4689  False
     3      4  -0.5527  0.025  -1.055 -0.0505   True
----------------------------------------------------

 [Tukey HSD 결과] v8안전장비착용여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   0.4059 0.1218 -0.0693  0.8811  False
     1      3   1.0741    0.0  0.6081    1.54   True
     1      4   0.2721 0.4348 -0.1984  0.7425  False
     2      3   0.6681 0.0022  0.1929  1.1434   True
     2      4  -0.1338 0.8852 -0.6134  0.3457  False
     3      4   -0.802 0.0001 -1.2724 -0.3316   True
----------------------------------------------------

 [Tukey HSD 결과] v9보험가입여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.5156 0.0007 -0.8516 -0.1795   True
     1      3  -0.7407    0.0 -1.0703 -0.4112   True
     1      4  -0.5556 0.0002 -0.8883 -0.2228   True
     2      3  -0.2252 0.3035 -0.5613  0.1109  False
     2      4    -0.04 0.9898 -0.3792  0.2992  False
     3      4   0.1852 0.4691 -0.1475  0.5179  False
----------------------------------------------------

 [Tukey HSD 결과] v10음주여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.0281 0.9936 -0.3074 0.2511  False
     1      3   0.0741 0.8941 -0.1997 0.3479  False
     1      4   0.0602 0.9444  -0.222 0.3424  False
     2      3   0.1022 0.7742  -0.177 0.3814  False
     2      4   0.0883 0.8529 -0.1992 0.3758  False
     3      4  -0.0139 0.9992 -0.2961 0.2683  False
---------------------------------------------------

 [Tukey HSD 결과] v11사고경험
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.1852 0.1438 -0.4099  0.0396  False
     1      3   0.1111 0.5543 -0.1093  0.3315  False
     1      4  -0.1852 0.1374 -0.4077  0.0373  False
     2      3   0.2963 0.0046  0.0716   0.521   True
     2      4      0.0    1.0 -0.2268  0.2268  False
     3      4  -0.2963 0.0041 -0.5188 -0.0738   True
----------------------------------------------------

 [Tukey HSD 결과] v12안전불안감
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.6148 0.2092 -1.4333 0.2036  False
     1      3  -0.1481 0.9629 -0.9507 0.6544  False
     1      4  -0.0456 0.9989 -0.8558 0.7646  False
     2      3   0.4667 0.4476 -0.3518 1.2851  False
     2      4   0.5692 0.2792 -0.2567 1.3952  False
     3      4   0.1026 0.9875 -0.7077 0.9128  False
---------------------------------------------------

 [Tukey HSD 결과] v14위험장소
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2    0.597 0.1872 -0.1747  1.3688  False
     1      3   0.0741 0.9941 -0.6827  0.8309  False
     1      4   -0.386 0.5525 -1.1501   0.378  False
     2      3   -0.523 0.2937 -1.2947  0.2488  False
     2      4  -0.9831 0.0073  -1.762 -0.2042   True
     3      4  -0.4601 0.3985 -1.2241  0.3039  False
----------------------------------------------------

 [Tukey HSD 결과] v19접근성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.4133 0.6841 -0.5592 1.3859  False
     1      3   0.4815 0.5531 -0.4722 1.4351  False
     1      4  -0.2051 0.9446 -1.1679 0.7576  False
     2      3   0.0681 0.9978 -0.9044 1.0407  False
     2      4  -0.6185 0.3578 -1.5999  0.363  False
     3      4  -0.6866 0.2506 -1.6494 0.2762  False
---------------------------------------------------

 [Tukey HSD 결과] v20대여 및 반납
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.6578 0.2056 -1.5293  0.2137  False
     1      3  -0.7778  0.088 -1.6324  0.0768  False
     1      4   -1.547 0.0001 -2.4098 -0.6842   True
     2      3    -0.12  0.984 -0.9915  0.7515  False
     2      4  -0.8892 0.0465 -1.7688 -0.0097   True
     3      4  -0.7692 0.0982  -1.632  0.0935  False

In [212]:
for col in significant_columns:
    print(f"\n [Tukey HSD 결과] {col}")
    tukey = pairwise_tukeyhsd(endog=data[col].dropna(),
                              groups=data['v3소속대학'][data[col].notna()],
                              alpha=0.05)
    print(tukey.summary())
    _ = None

 [Tukey HSD 결과] v5이용목적
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.7692 0.2491 -1.8104  0.2719  False
     1      3  -1.5385 0.0008 -2.5796 -0.4973   True
     1      4   1.4615  0.127 -0.2386  3.1617  False
     1      5   -0.602 0.2421 -1.4105  0.2066  False
     2      3  -0.7692 0.2491 -1.8104  0.2719  False
     2      4   2.2308 0.0038  0.5306  3.9309   True
     2      5   0.1673 0.9785 -0.6413  0.9759  False
     3      4      3.0    0.0  1.2999  4.7001   True
     3      5   0.9365 0.0147  0.1279  1.7451   True
     4      5  -2.0635 0.0037  -3.632 -0.4949   True
----------------------------------------------------

 [Tukey HSD 결과] v6이용빈도
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.7692 0.6101  -2.264  0.7255  False
     1      3   1.1538 0.2097 -0.3409  2.6486  False
     1      4   1.3846 0.5162 -1.0563  3.8255  False
     1      5  -0.4408 0.8289 -1.6017  0.7201  False
     2      3   1.9231 0.0048  0.4283  3.4178   True
     2      4   2.1538 0.1104  -0.287  4.5947  False
     2      5   0.3284 0.9341 -0.8324  1.4893  False
     3      4   0.2308 0.9989 -2.2101  2.6717  False
     3      5  -1.5946 0.0021 -2.7555 -0.4338   True
     4      5  -1.8254 0.1695 -4.0774  0.4266  False
----------------------------------------------------

 [Tukey HSD 결과] v7이용시간대
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.2308 0.9239 -1.0127 0.5512  False
     1      3  -0.5385 0.3172 -1.3204 0.2435  False
     1      4   0.7692 0.4548 -0.5076 2.0461  False
     1      5   0.0391 0.9998 -0.5682 0.6463  False
     2      3  -0.3077 0.8096 -1.0896 0.4742  False
     2      4      1.0 0.1974 -0.2769 2.2769  False
     2      5   0.2698 0.7313 -0.3374 0.8771  False
     3      4   1.3077  0.042  0.0308 2.5846   True
     3      5   0.5775 0.0704 -0.0297 1.1848  False
     4      5  -0.7302 0.4253 -1.9082 0.4479  False
---------------------------------------------------

 [Tukey HSD 결과] v8안전장비착용여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.3077 0.7983 -1.0743  0.4589  False
     1      3  -0.6923 0.0968 -1.4589  0.0743  False
     1      4   1.3077  0.036  0.0558  2.5596   True
     1      5  -0.1526 0.9533  -0.748  0.4428  False
     2      3  -0.3846 0.6331 -1.1513   0.382  False
     2      4   1.6154 0.0047  0.3635  2.8673   True
     2      5   0.1551 0.9506 -0.4403  0.7505  False
     3      4      2.0 0.0002  0.7481  3.2519   True
     3      5   0.5397 0.0947 -0.0557  1.1351  False
     4      5  -1.4603 0.0059 -2.6153 -0.3053   True
----------------------------------------------------

 [Tukey HSD 결과] v9보험가입여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.3846 0.2467 -0.9038  0.1346  False
     1      3   0.3077 0.4717 -0.2115  0.8269  False
     1      4  -0.3846  0.716 -1.2325  0.4633  False
     1      5  -0.4322 0.0293 -0.8355  -0.029   True
     2      3   0.6923 0.0031  0.1731  1.2115   True
     2      4      0.0    1.0 -0.8479  0.8479  False
     2      5  -0.0476 0.9975 -0.4509  0.3556  False
     3      4  -0.6923 0.1639 -1.5402  0.1556  False
     3      5  -0.7399    0.0 -1.1432 -0.3367   True
     4      5  -0.0476 0.9998 -0.8299  0.7346  False
----------------------------------------------------

 [Tukey HSD 결과] v11사고경험
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.3846 0.0213 -0.7303 -0.039   True
     1      3  -0.3846 0.0213 -0.7303 -0.039   True
     1      4  -0.3846 0.3278  -0.949 0.1798  False
     1      5  -0.2576 0.0664 -0.5261 0.0108  False
     2      3      0.0    1.0 -0.3456 0.3456  False
     2      4      0.0    1.0 -0.5644 0.5644  False
     2      5    0.127 0.6831 -0.1415 0.3954  False
     3      4      0.0    1.0 -0.5644 0.5644  False
     3      5    0.127 0.6831 -0.1415 0.3954  False
     4      5    0.127 0.9609 -0.3938 0.6477  False
---------------------------------------------------

 [Tukey HSD 결과] v14위험장소
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -1.1538 0.0362 -2.2591 -0.0486   True
     1      3  -0.8462 0.2169 -1.9514  0.2591  False
     1      4   1.1538 0.3932  -0.651  2.9587  False
     1      5  -1.0049 0.0132 -1.8633 -0.1465   True
     2      3   0.3077 0.9377 -0.7975  1.4129  False
     2      4   2.3077 0.0052  0.5028  4.1125   True
     2      5    0.149 0.9888 -0.7094  1.0073  False
     3      4      2.0 0.0221  0.1952  3.8048   True
     3      5  -0.1587 0.9858 -1.0171  0.6996  False
     4      5  -2.1587 0.0044 -3.8239 -0.4936   True
----------------------------------------------------

 [Tukey HSD 결과] v15사고원인
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.3077 0.9876 -1.4169 2.0322  False
     1      3  -0.2308 0.9959 -1.9553 1.4938  False
     1      4  -0.7692 0.9416 -3.5854 2.0469  False
     1      5   0.2308 0.9891 -1.1086 1.5701  False
     2      3  -0.5385 0.9081  -2.263 1.1861  False
     2      4  -1.0769 0.8252 -3.8931 1.7392  False
     2      5  -0.0769 0.9999 -1.4163 1.2624  False
     3      4  -0.5385 0.9839 -3.3546 2.2777  False
     3      5   0.4615 0.8734 -0.8778 1.8009  False
     4      5      1.0 0.8218 -1.5982 3.5982  False
---------------------------------------------------

 [Tukey HSD 결과] v17편리성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2      1.0 0.1369 -0.1803 2.1803  False
     1      3   0.3846 0.8942 -0.7957 1.5649  False
     1      4   0.6154 0.9011  -1.312 2.5428  False
     1      5   0.3297 0.8552  -0.587 1.2463  False
     2      3  -0.6154 0.5981 -1.7957 0.5649  False
     2      4  -0.3846 0.9812  -2.312 1.5428  False
     2      5  -0.6703 0.2587  -1.587 0.2463  False
     3      4   0.2308 0.9973 -1.6966 2.1582  False
     3      5  -0.0549 0.9998 -0.9716 0.8617  False
     4      5  -0.2857 0.9917 -2.0639 1.4925  False
---------------------------------------------------

 [Tukey HSD 결과] v18안전성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.3846 0.8844 -1.5331 0.7639  False
     1      3  -0.4615 0.7975   -1.61 0.6869  False
     1      4   1.1538  0.433 -0.7216 3.0293  False
     1      5  -0.4493 0.6294 -1.3413 0.4426  False
     2      3  -0.0769 0.9997 -1.2254 1.0715  False
     2      4   1.5385 0.1604  -0.337 3.4139  False
     2      5  -0.0647 0.9996 -0.9567 0.8272  False
     3      4   1.6154 0.1257 -0.2601 3.4908  False
     3      5   0.0122    1.0 -0.8797 0.9042  False
     4      5  -1.6032  0.083 -3.3335 0.1271  False
---------------------------------------------------

 [Tukey HSD 결과] v20대여 및 반납
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2   2.3077    0.0  1.0534  3.5619   True
     1      3   0.7692 0.4363  -0.485  2.0235  False
     1      4   1.6923  0.155 -0.3559  3.7405  False
     1      5   0.5018 0.6091 -0.4723  1.4759  False
     2      3  -1.5385 0.0082 -2.7927 -0.2842   True
     2      4  -0.6154 0.9192 -2.6636  1.4328  False
     2      5  -1.8059    0.0   -2.78 -0.8318   True
     3      4   0.9231 0.7209 -1.1251  2.9713  False
     3      5  -0.2674 0.9406 -1.2415  0.7067  False
     4      5  -1.1905 0.4084 -3.0801  0.6992  False
----------------------------------------------------

 [Tukey HSD 결과] v21사고 목격 경험
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.3846 0.1944 -0.8739 0.1047  False
     1      3   0.3077 0.4104 -0.1816  0.797  False
     1      4   0.6154 0.2117 -0.1837 1.4144  False
     1      5  -0.0354  0.999 -0.4154 0.3446  False
     2      3   0.6923 0.0014   0.203 1.1816   True
     2      4      1.0 0.0066   0.201  1.799   True
     2      5   0.3492 0.0873 -0.0308 0.7292  False
     3      4   0.3077 0.8215 -0.4914 1.1067  False
     3      5  -0.3431 0.0969 -0.7231 0.0369  False
     4      5  -0.6508 0.1101  -1.388 0.0864  False
---------------------------------------------------

 [Tukey HSD 결과] v22보호장비 착용 필요도
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.0769 0.9997  -1.244 1.0901  False
     1      3   0.4615 0.8068 -0.7055 1.6286  False
     1      4  -0.8462 0.7319  -2.752 1.0597  False
     1      5   0.1856 0.9793 -0.7208  1.092  False
     2      3   0.5385 0.7029 -0.6286 1.7055  False
     2      4  -0.7692 0.7949  -2.675 1.1366  False
     2      5   0.2625 0.9286 -0.6439 1.1689  False
     3      4  -1.3077 0.3208 -3.2135 0.5981  False
     3      5  -0.2759 0.9155 -1.1823 0.6304  False
     4      5   1.0317 0.4819 -0.7266   2.79  False
---------------------------------------------------

 [Tukey HSD 결과] v23위험수준
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.0572 0.9997 -0.7397 0.8542  False
     1      3  -0.1185 0.9962 -1.0121  0.775  False
     1      4  -0.8519 0.0607 -1.7273 0.0236  False
     1      5   0.2815 0.6845 -0.3095 0.8725  False
     2      3  -0.1758 0.9852 -1.1049 0.7534  False
     2      4  -0.9091 0.0511 -1.8208 0.0026  False
     2      5   0.2242 0.8728 -0.4193 0.8678  False
     3      4  -0.7333 0.2581 -1.7306 0.2639  False
     3      5      0.4 0.5965 -0.3599 1.1599  False
     4      5   1.1333 0.0003  0.3948 1.8718   True
---------------------------------------------------

 [Tukey HSD 결과] v27음주 이용 사고 유발 가능성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.1717 0.8776 -0.6705  0.327  False
     1      3   0.4222 0.2334  -0.137 0.9814  False
     1      4   0.5556 0.0451  0.0077 1.1034   True
     1      5   0.2639 0.2874  -0.106 0.6338  False
     2      3   0.5939 0.0426  0.0125 1.1754   True
     2      4   0.7273  0.005  0.1567 1.2978   True
     2      5   0.4356 0.0268  0.0329 0.8383   True
     3      4   0.1333 0.9767 -0.4908 0.7574  False
     3      5  -0.1583 0.8902 -0.6339 0.3172  False
     4      5  -0.2917 0.4134 -0.7538 0.1705  False
---------------------------------------------------

 [Tukey HSD 결과] v28보험 가입 의무화 필요성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.6044 0.5621 -0.5032  1.712  False
     1      3  -0.1926  0.993 -1.4345 1.0493  False
     1      4   0.4907 0.8008 -0.7259 1.7074  False
     1      5   0.1407 0.9898 -0.6807 0.9622  False
     2      3   -0.797 0.4367 -2.0883 0.4943  False
     2      4  -0.1136 0.9992 -1.3807 1.1534  False
     2      5  -0.4636 0.6108  -1.358 0.4308  False
     3      4   0.6833 0.6555 -0.7027 2.0693  False
     3      5   0.3333 0.9079 -0.7228 1.3895  False
     4      5    -0.35 0.8814 -1.3764 0.6764  False
---------------------------------------------------

 [Tukey HSD 결과] v29인도 주행 허용 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.4125 0.7846 -1.4079  0.5829  False
     1      3   1.0815 0.0625 -0.0346  2.1976  False
     1      4  -1.1227  0.041 -2.2161 -0.0293   True
     1      5  -1.0602  0.001 -1.7984  -0.322   True
     2      3   1.4939 0.0044  0.3335  2.6544   True
     2      4  -0.7102 0.4257 -1.8489  0.4285  False
     2      5  -0.6477 0.1771 -1.4515  0.1561  False
     3      4  -2.2042    0.0 -3.4497 -0.9586   True
     3      5  -2.1417    0.0 -3.0908 -1.1925   True
     4      5   0.0625 0.9997 -0.8599  0.9849  False
----------------------------------------------------

 [Tukey HSD 결과] v30특정 구간 속도 제한 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.0421 0.9998 -0.6945 0.6103  False
     1      3   0.3185  0.752  -0.413   1.05  False
     1      4   0.8102  0.018  0.0935 1.5269   True
     1      5   0.5352  0.022  0.0513  1.019   True
     2      3   0.3606 0.6882    -0.4 1.1212  False
     2      4   0.8523 0.0163  0.1059 1.5986   True
     2      5   0.5773 0.0239  0.0504 1.1041   True
     3      4   0.4917 0.4623 -0.3247 1.3081  False
     3      5   0.2167 0.8731 -0.4054 0.8388  False
     4      5   -0.275 0.7205 -0.8796 0.3296  False
---------------------------------------------------

 [Tukey HSD 결과] v31번호판, 반사테이프 부착 의무화 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.1465 0.9577 -0.4351  0.728  False
     1      3  -0.0444 0.9997 -0.6965 0.6076  False
     1      4   0.1806 0.9366 -0.4583 0.8194  False
     1      5  -0.0694 0.9919 -0.5008 0.3619  False
     2      3  -0.1909 0.9375 -0.8689 0.4871  False
     2      4   0.0341 0.9999 -0.6312 0.6994  False
     2      5  -0.2159 0.7124 -0.6855 0.2537  False
     3      4    0.225  0.914 -0.5027 0.9527  False
     3      5   -0.025 0.9999 -0.5795 0.5295  False
     4      5    -0.25 0.7055 -0.7889 0.2889  False
---------------------------------------------------

 [Tukey HSD 결과] v32면허증 강화 필요성
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.0539 0.9996 -0.6486 0.7563  False
     1      3   0.0963 0.9972 -0.6913 0.8839  False
     1      4    0.588 0.2251 -0.1837 1.3596  False
     1      5   0.3213 0.4375 -0.1997 0.8423  False
     2      3   0.0424 0.9999 -0.7765 0.8614  False
     2      4   0.5341 0.3593 -0.2695 1.3377  False
     2      5   0.2674 0.6927 -0.2998 0.8347  False
     3      4   0.4917 0.5377 -0.3873 1.3707  False
     3      5    0.225  0.887 -0.4448 0.8948  False
     4      5  -0.2667 0.7916 -0.9176 0.3843  False
---------------------------------------------------

 [Tukey HSD 결과] v33반납 장소 지정 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.0707 0.9981 -0.5683 0.7097  False
     1      3   0.4889 0.3321 -0.2275 1.2053  False
     1      4   0.7014 0.0503 -0.0005 1.4033  False
     1      5   0.4639 0.0582   -0.01 0.9378  False
     2      3   0.4182 0.5341 -0.3268 1.1631  False
     2      4   0.6307 0.1264 -0.1003 1.3617  False
     2      5   0.3932  0.225 -0.1228 0.9091  False
     3      4   0.2125 0.9489 -0.5871 1.0121  False
     3      5   -0.025    1.0 -0.6343 0.5843  False
     4      5  -0.2375 0.8041 -0.8296 0.3546  False
---------------------------------------------------

 [Tukey HSD 결과] v34안전 수칙 위반 처벌 및 단속 강화 필요 여부
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2   0.1532 0.9767 -0.5637 0.8701  False
     1      3   0.1926 0.9646 -0.6112 0.9964  False
     1      4   0.7384 0.0777 -0.0491 1.5259  False
     1      5   0.3426 0.3916 -0.1891 0.8743  False
     2      3   0.0394 0.9999 -0.7964 0.8752  False
     2      4   0.5852 0.2872 -0.2349 1.4054  False
     2      5   0.1894 0.8963 -0.3895 0.7683  False
     3      4   0.5458 0.4516 -0.3513 1.4429  False
     3      5     0.15 0.9743 -0.5336 0.8336  False
     4      5  -0.3958 0.4734 -1.0602 0.2685  False
---------------------------------------------------

 [Tukey HSD 결과] v5이용목적
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.7692 0.2491 -1.8104  0.2719  False
     1      3  -1.5385 0.0008 -2.5796 -0.4973   True
     1      4   1.4615  0.127 -0.2386  3.1617  False
     1      5   -0.602 0.2421 -1.4105  0.2066  False
     2      3  -0.7692 0.2491 -1.8104  0.2719  False
     2      4   2.2308 0.0038  0.5306  3.9309   True
     2      5   0.1673 0.9785 -0.6413  0.9759  False
     3      4      3.0    0.0  1.2999  4.7001   True
     3      5   0.9365 0.0147  0.1279  1.7451   True
     4      5  -2.0635 0.0037  -3.632 -0.4949   True
----------------------------------------------------

 [Tukey HSD 결과] v6이용빈도
Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     1      2  -0.7692 0.6101  -2.264  0.7255  False
     1      3   1.1538 0.2097 -0.3409  2.6486  False
     1      4   1.3846 0.5162 -1.0563  3.8255  False
     1      5  -0.4408 0.8289 -1.6017  0.7201  False
     2      3   1.9231 0.0048  0.4283  3.4178   True
     2      4   2.1538 0.1104  -0.287  4.5947  False
     2      5   0.3284 0.9341 -0.8324  1.4893  False
     3      4   0.2308 0.9989 -2.2101  2.6717  False
     3      5  -1.5946 0.0021 -2.7555 -0.4338   True
     4      5  -1.8254 0.1695 -4.0774  0.4266  False
----------------------------------------------------

 [Tukey HSD 결과] v7이용시간대
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
     1      2  -0.2308 0.9239 -1.0127 0.5512  False
     1      3  -0.5385 0.3172 -1.3204 0.2435  False
     1      4   0.7692 0.4548 -0.5076 2.0461  False
     1      5   0.0391 0.9998 -0.5682 0.6463  False

In [218]:
import plotly.graph_objects as go
import plotly.express as px

In [217]:
values=['이용자 평균', '비이용자 평균']

fig = go.Figure([go.Bar(x=values, y=[2.171, 1.705])])
fig.show()

In [235]:
grouped_mean = data.groupby('v4_1이용여부')['v34안전 수칙 위반 처벌 및 단속 강화 필요 여부'].mean().reset_index()

# 막대그래프 시각화
fig = px.bar(
    grouped_mean,
    x='v4_1이용여부',
    y='v34안전 수칙 위반 처벌 및 단속 강화 필요 여부',
    text='v34안전 수칙 위반 처벌 및 단속 강화 필요 여부',
    labels={
        'v4_1이용여부': '이용 여부 (0: 비이용자, 1: 이용자)',
        'v34안전 수칙 위반 처벌 및 단속 강화 필요 여부': '처벌 및 단속 강화 필요 여부'
    },
    title='처벌 및 단속 강화 필요 여부 여부에 따른 평균 비교'
)
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig.update_layout(yaxis=dict(range=[0, 5]))
fig.show()

In [219]:
data

,v1성별,v2학년,v3소속대학,v5이용목적,v6이용빈도,v7이용시간대,v8안전장비착용여부,v9보험가입여부,v10음주여부,v11사고경험,...,v27음주 이용 사고 유발 가능성,v28보험 가입 의무화 필요성,v29인도 주행 허용 여부,v30특정 구간 속도 제한 여부,"v31번호판, 반사테이프 부착 의무화 여부",v32면허증 강화 필요성,v33반납 장소 지정 여부,v34안전 수칙 위반 처벌 및 단속 강화 필요 여부,v4이용종류,v4_1이용여부
0,1,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,2,3,4,4,4,5,5,3,0
1,2,1,3,1.0,5.0,2.0,1.0,3.0,1.0,1.0,...,5,4,4,4,4,4,5,4,1,1
2,1,4,5,2.0,1.0,3.0,1.0,2.0,1.0,1.0,...,5,2,1,5,4,4,5,5,2,1
3,1,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0
4,1,2,5,2.0,4.0,3.0,1.0,2.0,1.0,1.0,...,5,1,1,5,5,2,5,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2,3,2,2.0,1.0,3.0,1.0,2.0,1.0,1.0,...,4,4,2,4,5,4,4,3,2,1
196,1,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0
197,1,4,2,2.0,2.0,2.0,2.0,2.0,1.0,1.0,...,5,5,4,4,5,4,5,5,1,1
198,2,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0
199,2,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,5,1,5,5,5,5,5,3,0